### ISSUE TITLE
Would you be interested in sharing image-charts.com as an alternative ?

### ISSUE THREAD

**Issue by FGRibreau** [typpo/quickchart#1]
Hello !

2 years ago we've built an alternative to Google Image-Charts that use the **same API**.
It's fully hosted and distributed world-wide to offer the same generation speed and availability as Google Image Charts (<250ms), see our [website](https://www.image-charts.com/).

And it has a free tier to give back to the community, would it be possible to add a link to it from your repository?

**Comment by typpo** [comment]
Hi @FGRibreau, thanks for reaching out :) would be happy to do this if you want to share quickchart as an alternative on image-charts as well.  Otherwise, in the interest of fairness, I'd like to do a survey of all the various options and list them out at some point (image-charts included)
