### ISSUE TITLE
Save image not working

### ISSUE THREAD

**Issue by Px-dev-fr** [typpo/quickchart#106]
Hi ! 
I'm having an issue using quick chart with php. I'm trying to save this chart:
` $qc = new QuickChart();
        $qc->setConfig("{
        type: 'line',
        title: 'Evolution des resultats',
        data: 
            {
                labels :[".implode( ", ", $labelAnnees)."],
                datasets: [
                    {
                    label:'".$pdf->str("Evolution du CA")."',
                    data: [".implode( ", ", $valeurParLigne['CA'])."],
                    fill: false
                    },
                    {
                    label:'".$pdf->str("Evolution de l\'EBITDA")."',
                    data: [".implode( ", ", $valeurParLigne['EBITDA'])."],
                    fill: false
                    },
                    {
                    label:'".$pdf->str("Evolution du resultat net")."',
                    data: [".implode( ", ", $valeurParLigne['RN'])."],
                    fill: false
                    }
                ]
            },
        `}");``
When i'm using qc->toFile(mypath).

While looking the cause of the error i noticed that qc->getUrl() was working and that the variable result inside this function (used to save the file had a false value.
`function toBinary() {
    $ch = curl_init($this->getRootEndpoint() . '/chart');
    $postData = array(
      'backgroundColor' => $this->backgroundColor,
      'width' => $this->width,
      'height' => $this->height,
      'format' => $this->format,
      'chart' => $this->getConfigStr(),
    );
    if ($this->apiKey) {
      $postData['key'] = $this->apiKey;
    }
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($postData));
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $result = curl_exec($ch);
    curl_close($ch);
    return $result;
  }`

Thanks in adavance for your help

**Comment by Px-dev-fr** [comment]
Fixed it with 
`file_put_contents(__DIR__."/my_graph.png", file_get_contents($qc->getUrl()));`

**Comment by typpo** [comment]
I can't debug this without an error message, but [this example](https://github.com/typpo/quickchart-php/blob/main/examples/to_file.php) works ok with PHP 7
