### ISSUE TITLE
devicePixelRatio has multiple defaults

### ISSUE THREAD

**Issue by screencomuser** [typpo/quickchart#108]
When using `getUrl` the devicePixelRatio parameter is only appended if it is different from `1.0`

However, the /chart endpoint uses a default value of `2.0` when the query parameter has not been given.

It would be helpful if both the generation as the handling of the url to create a chart would decide on a common value.

End users can apply the following quick fix in their code

```javascript
      const url = new URL(chart.getUrl());
      url.searchParams.append('devicePixelRatio', '1');
      return url.href;
```

**Comment by typpo** [comment]
Thanks, this is a known issue.  1.0 is a better default, but the web API must keep the default of 2.0 for backwards compatibility reasons.  The next version of the API will likely default to devicePixelRatio=1 across all surfaces.

**Comment by screencomuser** [comment]
Thanks for the heads-up.

I can see where changing this would lead to all sorts of unwanted behaviour.
