### ISSUE TITLE
Can I change the reference point? 

### ISSUE THREAD

**Issue by wiresharkkkk** [typpo/quickchart#110]
I want to change the reference point from 0 to something else.
For example 10...

And I want the fill color to be different for data lower than the reference point.

Any examples of this?

**Comment by typpo** [comment]
If by reference point you mean axis, you set `options.scales.yAxes[0].ticks.min`.  [Example](https://quickchart.io/sandbox/#%7B%0A%20%20type%3A%20'bar'%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B'Q1'%2C%20'Q2'%2C%20'Q3'%2C%20'Q4'%5D%2C%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20label%3A%20'Users'%2C%0A%20%20%20%20%20%20data%3A%20%5B50%2C%2060%2C%2070%2C%20180%5D%0A%20%20%20%20%7D%5D%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20scales%3A%20%7B%0A%20%20%20%20%20%20yAxes%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20ticks%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20min%3A%2010%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

The best way to fill under a certain value is by combining the `fill` property with a second dataset that defines the "reference point".  [Here's an example](https://quickchart.io/sandbox/#%7B%0A%20%20type%3A%20'line'%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B'Q1'%2C%20'Q2'%2C%20'Q3'%2C%20'Q4'%5D%2C%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20label%3A%20'Revenue'%2C%0A%20%20%20%20%20%20data%3A%20%5B10%2C%2010%2C%2010%2C%2010%5D%2C%0A%20%20%20%20%20%20fill%3A%20'start'%2C%0A%20%20%20%20%20%20borderWidth%3A%200%2C%0A%20%20%20%20%20%20pointRadius%3A%200%2C%0A%20%20%20%20%20%20borderColor%3A%20'rgba(0%2C%20255%2C%200%2C%200.2)'%2C%0A%20%20%20%20%20%20backgroundColor%3A%20'rgba(0%2C%20255%2C%200%2C%200.2)'%2C%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20label%3A%20'Data'%2C%0A%20%20%20%20%20%20data%3A%20%5B56.5%2C%2058.5%2C%2052.5%2C%2049.5%2C%2053.5%2C%2049.5%2C%2052%2C%2048.5%2C%2057%2C%2058%2C%2052%2C%2052.5%2C%2050.5%2C%2051%5D%2C%0A%20%20%20%20%20%20fill%3A%20'-1'%2C%0A%20%20%20%20%7D%5D%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20scales%3A%20%7B%0A%20%20%20%20%20%20yAxes%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20stacked%3A%20true%2C%0A%20%20%20%20%20%20%20%20ticks%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20min%3A%20-10%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20legend%3A%20%7B%0A%20%20%20%20%20%20display%3A%20false%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D%2C%0A%7D%0A) of a graph with a min y value of -10 with a line that fills a different color below y=10.

Refer to the [Chart.js documentation](https://www.chartjs.org/docs/2.9.4/charts/line.html#dataset-properties) on line dataset properties.

<img src="https://user-images.githubusercontent.com/310310/136703425-62be03de-cc6f-4e00-874a-df37ffcd0626.png" width="500">
