### ISSUE TITLE
dataset with `undefined` entries results in 500

### ISSUE THREAD

**Issue by rayhatfield** [typpo/quickchart#114]
I've declared a dataset that includes several `undefined` entries[^1], and this results in a 500 error.

```js
data: [
  undefined,
  undefined,
  { x: 0, y: 180 },
  { x: 1, y: 180 },
],
```

Interestingly, this occurs in my local container running the published docker image but seems fine (does not 500) on quickchart.io.

I've tracked it down to the [fixNodeVmObject](https://github.com/typpo/quickchart/blob/d291e645a7267ae01b09015311f161878f54a618/lib/util.js#L10) function in `./lib/utils.js`. This recursive call ends up invoking itself on the undefined entries, at which point `Object.keys(undefined)` throws:

```js
function fixNodeVmObject(obj) {
  // Fix for https://github.com/patriksimek/vm2/issues/198
  const objKeys = Object.keys(obj);
  ...
```

A simple fix would be to bail if `obj` is falsy, and I'll submit a PR accordingly.

[^1]: I'd originally put the undefined entries in there because the data starts late on the x axis. I've since figured out a better approach but I still think it's reasonable to expect this to not throw.

**Comment by typpo** [comment]
Thanks for catching this, closing because I've merged your fix in #115
