### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by feralheart** [typpo/quickchart#116]
The documentation is inaccurate and/or outdated.
For example the return of the POST request is the generated chart's image and not a `{success: bool, url: string }` object

**Comment by typpo** [comment]
Which documentation are you referring to?  POST to `/chart` will return an image.  The `{success, url}` response is returned by POSTing to the `/chart/create` endpoint, which creates shortened URLs.  https://quickchart.io/documentation/#post-endpoint

**Comment by feralheart** [comment]
I've tried to send a request to `chart/create`, but I've got a 'Cannot POST /chart/create' response. Is it available in the self-hosted version as well?

**Comment by typpo** [comment]
Unfortunately, short URL creation is not part of the self-hosted version.  This is because it requires a persistent data store.  quickchart.io's implementation doesn't translate well to self-hosting, so it's not part of this project right now.
