### ISSUE TITLE
100% stacked bar chart?

### ISSUE THREAD

**Issue by kartnan** [typpo/quickchart#125]
Is there anyway to create a 100% stacked horizontal bar chart?

**Comment by typpo** [comment]
Hello,

it is indeed possible, but the approach is a little strange without a plugin.  You have to make sure that datapoint _n_ from each dataset adds up to the same amount.  This example uses a `horizontalBar` chart type (Chart.js v2) and arrays of `backgroundColor`s:

![image](https://user-images.githubusercontent.com/310310/157817594-60bb2985-b964-45de-a6ae-83fdd3956b2a.png)

[editor link](https://quickchart.io/sandbox/#%7B%22chart%22%3A%22%7B%5Cn%20%20type%3A%20'horizontalBar'%2C%5Cn%20%20data%3A%20%7B%5Cn%20%20%20%20labels%3A%20%5B'Label%201'%2C%20'Label%202'%5D%2C%5Cn%20%20%20%20datasets%3A%20%5B%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20backgroundColor%3A%20%5B'%23fd5a3e'%2C%20null%5D%2C%5Cn%20%20%20%20%20%20%20%20data%3A%20%5B0.5%2C%20null%5D%2C%5Cn%20%20%20%20%20%20%20%20barThickness%3A%2030%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20backgroundColor%3A%20%5B'%23ffd050'%2C%20'%2397cc64'%5D%2C%5Cn%20%20%20%20%20%20%20%20data%3A%20%5B0.5%2C%201.0%5D%2C%5Cn%20%20%20%20%20%20%20%20barThickness%3A%2030%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%5D%2C%5Cn%20%20%7D%2C%5Cn%20%20options%3A%20%7B%5Cn%20%20%20%20legend%3A%20%7B%5Cn%20%20%20%20%20%20position%3A%20'bottom'%2C%5Cn%20%20%20%20%20%20labels%3A%20%7B%5Cn%20%20%20%20%20%20%20%20generateLabels%3A%20(chart)%20%3D%3E%20%5B%5Cn%20%20%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20'Failed'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20fillStyle%3A%20'%23fd5a3e'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20'Broken'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20fillStyle%3A%20'%23ffd050'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20'Passed'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20fillStyle%3A%20'%2397cc64'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%5D%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20scales%3A%20%7B%5Cn%20%20%20%20%20%20xAxes%3A%20%5B%5Cn%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20stacked%3A%20true%2C%5Cn%20%20%20%20%20%20%20%20%20%20ticks%3A%20%7B%20min%3A%200%2C%20max%3A%201%2C%20display%3A%20false%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20gridLines%3A%20%7B%20display%3A%20false%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%5D%2C%5Cn%20%20%20%20%20%20yAxes%3A%20%5B%7B%20stacked%3A%20true%2C%20gridLines%3A%20%7B%20drawBorder%3A%20false%20%7D%20%7D%5D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20plugins%3A%20%7B%5Cn%20%20%20%20%20%20datalabels%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20true%2C%5Cn%20%20%20%20%20%20%20%20color%3A%20'%23fff'%2C%5Cn%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20style%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20formatter%3A%20()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20return%20'1'%3B%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%7D%2C%5Cn%7D%3B%5Cn%22%2C%22width%22%3A500%2C%22height%22%3A150%2C%22version%22%3A%222%22%2C%22backgroundColor%22%3A%22%23fff%22%7D)

```
{
  type: 'horizontalBar',
  data: {
    labels: ['Label 1', 'Label 2'],
    datasets: [
      {
        backgroundColor: ['#fd5a3e', null],
        data: [0.5, null],
        barThickness: 30,
      },
      {
        backgroundColor: ['#ffd050', '#97cc64'],
        data: [0.5, 1.0],
        barThickness: 30,
      },
    ],
  },
  options: {
    legend: {
      position: 'bottom',
      labels: {
        generateLabels: (chart) => [
          {
            text: 'Failed',
            fillStyle: '#fd5a3e',
          },
          {
            text: 'Broken',
            fillStyle: '#ffd050',
          },
          {
            text: 'Passed',
            fillStyle: '#97cc64',
          },
        ],
      },
    },
    scales: {
      xAxes: [
        {
          stacked: true,
          ticks: { min: 0, max: 1, display: false },
          gridLines: { display: false },
        },
      ],
      yAxes: [{ stacked: true, gridLines: { drawBorder: false } }],
    },
    plugins: {
      datalabels: {
        display: true,
        color: '#fff',
        font: {
          style: 'bold',
        },
        formatter: () => {
          return '1';
        },
      },
    },
  },
}
```

Hope this helps!
