### ISSUE TITLE
formatter not working in apex chart

### ISSUE THREAD

**Issue by GabrielLucasSBG** [typpo/quickchart#126]
when I try to use the formatter in an apex chart, it doesn't work, generating errors

**Comment by npltr62** [comment]
I have the same issue too,  @GabrielLucasSBG  do you find something to resolve it?

**Comment by typpo** [comment]
Hi @GabrielLucasSBG and @npltr62, the apex charts renderer has been upgraded to include support for formatters.  Here's an example:

```javascript
{
    chart: {
        type: 'line'
    },
    series: [{
        name: 'sales',
        data: [31, 40, 35, 50, 49, 60, 70, 91, 125]
    }],
    xaxis: {
        categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
    },
    yaxis: {
        labels: {
            formatter: function(value) {
                return '$' + value;
            }
        },
    },
}
```

[Link](https://quickchart.io/apex-charts/render?config=%7B%0A%20%20chart%3A%20%7B%0A%20%20%20%20type%3A%20%27line%27%0A%20%20%7D%2C%0A%20%20series%3A%20%5B%7B%0A%20%20%20%20name%3A%20%27sales%27%2C%0A%20%20%20%20data%3A%20%5B31%2C40%2C35%2C50%2C49%2C60%2C70%2C91%2C125%5D%0A%20%20%7D%5D%2C%0A%20%20xaxis%3A%20%7B%0A%20%20%20%20categories%3A%20%5B1991%2C1992%2C1993%2C1994%2C1995%2C1996%2C1997%2C%201998%2C1999%5D%2C%0A%20%20%7D%2C%0A%20%20yaxis%3A%20%7B%0A%20%20%20%20labels%3A%20%7B%0A%20%20%20%20%20%20formatter%3A%20function%20%28value%29%20%7B%0A%20%20%20%20%20%20%20%20return%20%27%24%27%20%2B%20value%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%7D%2C%0A%7D)

![image](https://user-images.githubusercontent.com/310310/165009664-423719db-50d0-47b2-9e23-9978fa662fe2.png)
