### ISSUE TITLE
Docker image not work with null value in dataset

### ISSUE THREAD

**Issue by ericcma** [typpo/quickchart#130]
Hi,
I try to generate a chart image against a locally hosted image service. Use your sample link and just replace one data item with null,  then you will get a message "Internal Server Error" shows in the browser.

http://localhost:3400/chart?width=500&height=300&c={type:'bar',data:{labels:['January','February','March','April','May'],datasets:[{label:'Dogs',data:[50,null,70,180,190]},{label:'Cats',data:[100,200,300,400,500]}]}}

PS: the same dataset works in quickchart.io

Can you advise please?

Eric

**Comment by typpo** [comment]
Hi @ericcma, this should be fixed as of #115.  I've just tagged and release v1.6.0, available on docker: https://hub.docker.com/repository/docker/ianw/quickchart
