### ISSUE TITLE
Upgrade Nodejs version in Dockerfile

### ISSUE THREAD

**Issue by danbrad** [typpo/quickchart#139]
Node.js version is currently 12 in the Dockerfile, which is out of support.

Can it be upgraded to the current LTS version (18)?

**Comment by typpo** [comment]
Hi Dan - thanks for bringing this up.  I recall that the node upgrade somehow causes gradients to fail (this is part of the test suite).  Probably something weird to do with the native canvas dependency.  Will have to get to the bottom of that before updating the Dockerfile.
