### ISSUE TITLE
Cannot find guide on how  self-host

### ISSUE THREAD

**Issue by Mirko-Tebaldi** [typpo/quickchart#146]
Our team is trying some self-hosted solutions for server-side rendering of chartsJs .

We'd like to give a try to this package, but we cannot find how to install and run as a "local" server

**Comment by typpo** [comment]
Hi @Mirko-Tebaldi,

The best way to run QuickChart locally is with Docker.  See the instructions on running the Docker image [here](https://github.com/typpo/quickchart#running).  With Docker installed, this command will start up QuickChart: `docker run -p 8080:3400 ianw/quickchart`.
