### ISSUE TITLE
Cannot get POST working with docker

### ISSUE THREAD

**Issue by Jacek-ghub** [typpo/quickchart#148]
I have just installed docker image on Mac.  Looks like it is working, as /healthcheck returns {"success":true,"version":"1.7.1"} and /healthcheck/chart redirects to a chart image.  I have also run Python example for GET requests and got a working URL.

However, I cannot get POST to work.  When I POST against /chart/create, I am getting 404 error with HTML response "Cannot POST /chart/create" (as /chart/create is meant for POST, shouldn't response be in JSON format rather than HTML 404, as that response is not really meant to be human readable?).  I have also tried to POST against just /chart, and I get 200 response, but some binary data (maybe a png image, I didn't check it, but it would be great if that is the case).  In this case, I also cannot turn that response into JSON, as JSON parser throws exception (Expecting value: line 1 column 1 (char 0)) - well, binary data.

When I run that POST example against quickchart.io server, all is fine, so the problem is rather not with my Python code, but with the docker image.

**Comment by typpo** [comment]
Hi @Jacek-ghub, the `/chart/create` endpoint is not supported in the Docker version.  This is because the current implementation requires an external storage service.  

You're correct that the `/chart` returns binary data (the chart itself).  If you wish to produce short URLs locally, I recommend that you take the binary data and store a mapping from "short" string to image.

**Comment by Jacek-ghub** [comment]
Hi @typpo.  Thank you for the answer

I really don't care about those short URLs, so as long as /chart endpoint is design to work with POST and returns the chart itself, that would be exactly what I need.  Somehow looking at those examples, I thought that /chart is for GET and /chart/create for POST requests.  Again, thank you for clarifying that /chart works for both.

**Comment by Jacek-ghub** [comment]
Hi @typpo.  I am still struggling with POST response.  I do POST against /chart, and get back resp.status_code 200.  I assume that the data is in resp.text.  However, when I try to write that to a file (open('t.png', 'w+b')), I am getting an exception "a bytes-like object is required, not 'str'."  I am not sure what do I need to do with resp.text to be able to to save it as a png data.

When I look the file (written as a string), it clearly has the PNG data, but with extra encoding (most likely only non ASCII chars).  I am not really sure how to decode it.

**Comment by typpo** [comment]
Hey @Jacek-ghub, you might be interested in [quickchart-python](https://github.com/typpo/quickchart-python), specifically the `to_file` function.

If you want to roll your own, you may also look at the implementation: https://github.com/typpo/quickchart-python/blob/master/quickchart/__init__.py#L120

Specifically, it looks like `resp.content` is the way to go, not `resp.text`.

**Comment by Jacek-ghub** [comment]
Yeah, actually that is what I was just looking at. :)

I am new to Python, and when looking at Response object and some sample code, the resp.text was used everywhere, and this is what I was trying to use.

I completely missed the resp.content attribute there, and that one returns BYTES.  When you were writing your response, I was also looking at the same code you linked there.  However, you were much faster.

Thank you again so much for your help and tolerating my ignorance!!
