### ISSUE TITLE
PolarArea charts are displaying tooltips, how to disable?

### ISSUE THREAD

**Issue by KarelBrijs** [typpo/quickchart#15]
This is more of a question than an issue but since recent updates in your code all of a sudden there are tooltip labels on my chart. Ofcourse this is not what I want but I can't seem to disable them. Any suggestions on how to achieve this?

**Comment by typpo** [comment]
Hi @KarelBrijs, just pushed a change that should resolve this issue.  PolarArea chart was not correctly accounted for when setting defaults for a new label plugin.  Apologies for the unexpected tooltips.

I'm closing this now, but if you still see something unexpected please reply with an example and I will address it asap.
