### ISSUE TITLE
HTTP error 413 - payload too large

### ISSUE THREAD

**Issue by Jacek-ghub** [typpo/quickchart#150]
I have tried to create a scatter chart with a little over 2k data points.  My docker image returned HTTP error 413.  Is there a way to increase Node.js request payload size in the docker image (is that value exposed)?

**Comment by typpo** [comment]
The max URL length is set by the `--max-http-header-size` option given to node.  You can override it by editing the Dockerfile: https://github.com/typpo/quickchart/blob/master/Dockerfile#L33

**Comment by Jacek-ghub** [comment]
Yesterday, I installed Docker Desktop and pulled ianw/quickchart image from their repository.  I couldn't figure out how to modify Dockerfile on that pulled image.  I tried few docker CLI commands, but nothing worked for me.  I always ended up with 64k.  As I was not going anywhere with that, I abandoned pulled images.

After that, i downloaded the package from quickchart github, modified the Dockerfile, build it, run it, and looking at 'docker ps -a' command or image hierachy, the images still have 64k there, and of course, the server barfed on those bigger charts.  I removed that --max-... limit from the Dockerfile / startup command line, still the same thing.

I did some digging, and also looked at index.js.  Not sure why, but you are setting the json limit in two places in index.js and in Dockerfile.  Looks like the index.js takes precedence, so modifying Dockerfile has no effect (at least in my setup).  Also, for some reason, you try to limit both json and urlencoded.  I don't think that those two are needed, as it works for me with just expess.json limit (only tested with POST and scatter charts).  

Lastly, you are trying to use process.env.EXPRESS_JSON_LIMIT in that limit, but on my box (old Mac mini), that value is undefined.  Most likely you are using in in the official quickchart build.  So, that value '100kb' or-ed with that constant takes care of controlling at least the POST payload limit.

The good part of that express.json is that most likely it can be easily modified even in the docker pulled image.  

So, I would suggest removing that --max... from Dockerfile, remove express.urlencoded (or rather tested it more, as I just gave up when got my part working) and putting a comment next to that line for people that need to up that limit.

Actually, as it is kind of related to this issue.  I was trying to generate scatter charts.  One data point has format of '{ 'x':123, 'y': 456.789 }.'  Maybe it would worthwhile to add another option to chart format (e.g., data_raw: [[], [], ...]) that would instead use [123, 456.789] format.  That would eliminate 8 chars (in my case 20-30% of payload.  However, the server would need to convert that new dataset to the original format.  I have also noticed that doing json.dump in the postdata (on that chart) adds another 20-30% extra to the payload.  Maybe this could be also done on the server side to limit the bandwidth.  I guess, it depends what is more expensive on your production boxes (CPU usage or bandwidth).  I will try to do it on my side, as I generate roughly a couple of charts per day.

Again, thank you for pointing me to that Dockerfile, and giving me some hope to continue working on this.  My charts were just generated few minutes ago, so I am a happy camper!

**Comment by typpo** [comment]
Hey @Jacek-ghub, thanks for these suggestions around handling the URL length limits.  The limits logic is probably due for a cleanup.

It's worth noting that you already can create a more compact notation by using Javascript, for example to map over nested arrays. 

```js
{
  type: 'scatter',
  data: {
    datasets: [
      {
        label: 'Data',
        data: [[-49,40],[-59,-67],[84,-31],[-92,-50]].map(p => ({x:p[0],y:p[1]})),
      },
    ],
  }
}
```
