### ISSUE TITLE
Trying to generate "Quadrants" chart from gallery page

### ISSUE THREAD

**Issue by Jacek-ghub** [typpo/quickchart#151]
I was trying to generate [that chart](https://quickchart.io/sandbox#%7B%22chart%22%3A%22%7B%5Cn%20%20type%3A%20'scatter'%2C%5Cn%20%20data%3A%20%7B%5Cn%20%20%20%20datasets%3A%20%5B%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20label%3A%20'Data'%2C%5Cn%20%20%20%20%20%20%20%20data%3A%20%5B%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%20-1%2C%20y%3A%2010%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%20-15%2C%20y%3A%20-30%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%20-50%2C%20y%3A%2025%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%20-50%2C%20y%3A%20-75%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%2050%2C%20y%3A%20-75%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%5D%2C%5Cn%20%20%20%20%20%20%20%20backgroundColor%3A%20'red'%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20label%3A%20'Multicolor%20Data'%2C%5Cn%20%20%20%20%20%20%20%20data%3A%20%5B%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%20-10%2C%20y%3A%2010%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%20-75%2C%20y%3A%20-60%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%20-25%2C%20y%3A%2025%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%20-25%2C%20y%3A%20-40%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7B%20x%3A%2050%2C%20y%3A%2075%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%5D%2C%5Cn%20%20%20%20%20%20%20%20backgroundColor%3A%20%5B'green'%2C%20'blue'%2C%20'red'%2C%20'yellow'%2C%20'orange'%5D%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%5D%2C%5Cn%20%20%7D%2C%5Cn%20%20options%3A%20%7B%5Cn%20%20%20%20scales%3A%20%7B%5Cn%20%20%20%20%20%20x%3A%20%7B%5Cn%20%20%20%20%20%20%20%20min%3A%20-100%2C%5Cn%20%20%20%20%20%20%20%20max%3A%20100%2C%5Cn%20%20%20%20%20%20%20%20grid%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20drawBorder%3A%20false%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20y%3A%20%7B%5Cn%20%20%20%20%20%20%20%20min%3A%20-100%2C%5Cn%20%20%20%20%20%20%20%20max%3A%20100%2C%5Cn%20%20%20%20%20%20%20%20grid%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20drawBorder%3A%20false%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20plugins%3A%20%7B%5Cn%20%20%20%20%20%20annotation%3A%20%7B%5Cn%20%20%20%20%20%20%20%20annotations%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20Q1%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'box'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xMin%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xMax%3A%20100%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yMin%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yMax%3A%20100%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20'rgba(255%2C%2099%2C%20132%2C%200.25)'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20borderColor%3A%20'transparent'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20Q2%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'box'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xMin%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xMax%3A%20-100%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yMin%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yMax%3A%20100%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20'rgba(99%2C%20255%2C%20132%2C%200.25)'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20borderColor%3A%20'transparent'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20Q3%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'box'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xMin%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xMax%3A%20-100%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yMin%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yMax%3A%20-100%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20'rgba(99%2C%20132%2C%20255%2C%200.25)'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20borderColor%3A%20'transparent'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20Q4%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'box'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xMin%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xMax%3A%20100%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yMin%3A%200%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yMax%3A%20-100%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20'rgba(132%2C%20255%2C%20255%2C%200.25)'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20borderColor%3A%20'transparent'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20Label1%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2050%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yValue%3A%2090%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Quadrant%201'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20Label2%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%20-50%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yValue%3A%2090%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Quadrant%202'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20Label3%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%20-50%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yValue%3A%20-90%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Quadrant%203'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20Label4%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2050%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yValue%3A%20-90%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Quadrant%204'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%7D%2C%5Cn%7D%22%2C%22width%22%3A500%2C%22height%22%3A300%2C%22version%22%3A%223%22%2C%22backgroundColor%22%3A%22%23fff%22%7D) on my hosted box, but somehow couldn't make the quadrants to show.

I changed the code to point to QuickChart.io server and got mixed results.  When using v2 or v4 those quadrants were missing, and dots had wrong colors (both border and bgnd color).  However, when using v3, it produced the same chart as on it is on QuickChart.io example page (where that version is explicitly specified).  

Kind of minor thing, or maybe by design, with v3 the options/title/text was missing.  Also, you may note that "Multicolor Data" label has different color on QC.io and hosted charts.

The only difference was swapping the url from QC.io to my local box (same Python code; chart data from the QC example page - not modified, except the additional Title option; running project downloaded last week from Github in Docker).

QC.io / v3:
![QuickChart io-v3](https://user-images.githubusercontent.com/85920330/210310954-68024a4f-ba96-42bd-a501-ce5ae026c205.png)

QC.io / v2/4:
![QuickChart io-v4](https://user-images.githubusercontent.com/85920330/210311067-93db79b0-d5cb-494d-8b77-aff741d1512c.png)

Local hosted / v3/4:
![hosted-v3](https://user-images.githubusercontent.com/85920330/210311181-b59fa0cd-e9ed-474a-b95d-a9229890acad.png)

**Comment by typpo** [comment]
Hi @Jacek-ghub,

This chart relies on the Chart.js Annotations plugin, which is not yet supported in Chart.js v3+ on the self-hosted version (as noted in the [readme](https://github.com/typpo/quickchart#chartjs-versions), but easy to miss).

**Comment by Jacek-ghub** [comment]
Hi @typpo,

Yes, I missed that part.  I guess, when I initially read it, I didn't know anything about those plugins / restrictions.

Later, I relied on [docs page](https://quickchart.io/documentation/reference/chartjs-plugins/) that has no mention about self-hosted restrictions.  Further adding to my confusion was [annotations issue](https://github.com/typpo/quickchart/issues/74) which was working for v2.

I wanted to use those annotations for a monthly blood pressure chart.  It is not a big deal, as for that one, I can point to QC server (the worst case 2*31 * 3 data points, so it will work).
