### ISSUE TITLE
getGradientFillHelper() results in black background

### ISSUE THREAD

**Issue by cworsley4** [typpo/quickchart#155]
We have been using a chart based on the "annotated progress" bar chart demo. There seems to have been a change upstream of us, and perhaps Quickcharts where the gradient fill color results in a solid black.

Presumably the issue is associated with the getGadientFillHelper() method as is used in this [example](https://quickchart.io/sandbox#%7B%22chart%22%3A%22%7B%5Cn%20%20type%3A%20'bar'%2C%5Cn%20%20data%3A%20%7B%5Cn%20%20%20%20labels%3A%20%5B'Q1'%5D%2C%5Cn%20%20%20%20datasets%3A%20%5B%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20label%3A%20'Users'%2C%5Cn%20%20%20%20%20%20%20%20data%3A%20%5B100%5D%2C%5Cn%20%20%20%20%20%20%20%20backgroundColor%3A%20getGradientFillHelper('horizontal'%2C%20%5B%5Cn%20%20%20%20%20%20%20%20%20%20'green'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'yellow'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'orange'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'red'%2C%5Cn%20%20%20%20%20%20%20%20%5D)%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%5D%2C%5Cn%20%20%7D%2C%5Cn%20%20options%3A%20%7B%5Cn%20%20%20%20indexAxis%3A%20'y'%2C%5Cn%20%20%20%20layout%3A%20%7B%5Cn%20%20%20%20%20%20padding%3A%2040%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20scales%3A%20%7B%5Cn%20%20%20%20%20%20x%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20y%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20plugins%3A%20%7B%5Cn%20%20%20%20%20%20legend%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20annotation%3A%20%7B%5Cn%20%20%20%20%20%20%20%20clip%3A%20false%2C%5Cn%20%20%20%20%20%20%20%20common%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20drawTime%3A%20'afterDraw'%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20annotations%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20low%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%204%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Low'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20medium%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2050%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Medium'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20high%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2095%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'High'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20arrow%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'point'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20pointStyle%3A%20'triangle'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20'%23000'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20radius%3A%2015%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2075%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yAdjust%3A%2065%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20label1%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2075%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yAdjust%3A%2095%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Your%20score'%2C%20'75%25'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%7D%2C%5Cn%7D%22%2C%22width%22%3A500%2C%22height%22%3A150%2C%22version%22%3A%223%22%2C%22backgroundColor%22%3A%22%23fff%22%7D).

Repro: I didn't feel it necessary to post our own code as the example seems to be having the same issue. The examples specific url is: https://quickchart-urls.ty.workers.dev/annotated-progress-bar

If you remove one of the gradient colors from the given array (default, green, yellow, orange red) then you get a black background. Or if you remove an annotation (of type `label`) you get the same thing in response.

This could also be associated with annotations. In our own chart configuration we had a property `rotation` (mistakenly) on a label annotation that previously had no effect and now it does. 

Expected result:
![image](https://user-images.githubusercontent.com/1875169/213080582-90af4299-4153-437a-8c95-bba8864674fa.png)

Actual result:
![image](https://user-images.githubusercontent.com/1875169/213080478-a9532a06-e44d-45aa-9b8b-14407ff89253.png)
[Link](https://quickchart.io/sandbox#%7B%22chart%22%3A%22%7B%5Cn%20%20type%3A%20'bar'%2C%5Cn%20%20data%3A%20%7B%5Cn%20%20%20%20labels%3A%20%5B'Q1'%5D%2C%5Cn%20%20%20%20datasets%3A%20%5B%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20label%3A%20'Users'%2C%5Cn%20%20%20%20%20%20%20%20data%3A%20%5B100%5D%2C%5Cn%20%20%20%20%20%20%20%20backgroundColor%3A%20getGradientFillHelper('horizontal'%2C%20%5B%5Cn%20%20%20%20%20%20%20%20%20%20'green'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'yellow'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'orange'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'red'%2C%5Cn%20%20%20%20%20%20%20%20%5D)%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%5D%2C%5Cn%20%20%7D%2C%5Cn%20%20options%3A%20%7B%5Cn%20%20%20%20indexAxis%3A%20'y'%2C%5Cn%20%20%20%20layout%3A%20%7B%5Cn%20%20%20%20%20%20padding%3A%2040%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20scales%3A%20%7B%5Cn%20%20%20%20%20%20x%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20y%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20plugins%3A%20%7B%5Cn%20%20%20%20%20%20legend%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20annotation%3A%20%7B%5Cn%20%20%20%20%20%20%20%20clip%3A%20false%2C%5Cn%20%20%20%20%20%20%20%20common%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20drawTime%3A%20'afterDraw'%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20annotations%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20low%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%204%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Low'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20medium%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2050%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Medium'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20high%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2095%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'High'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20arrow%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'point'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20pointStyle%3A%20'triangle'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20'%23000'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20radius%3A%2015%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2075%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yAdjust%3A%2065%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20label1%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2075%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yAdjust%3A%2095%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Your%20score'%2C%20'75%25'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%7D%2C%5Cn%7D%22%2C%22width%22%3A500%2C%22height%22%3A150%2C%22version%22%3A%223%22%2C%22backgroundColor%22%3A%22%23fff%22%7D)

**Comment by cworsley4** [comment]
Also, this seems to be an issue with version 3 of Chart.js.

[This example](https://quickchart.io/sandbox#%7B%22chart%22%3A%22%7B%5Cn%20%20type%3A%20'bar'%2C%5Cn%20%20data%3A%20%7B%5Cn%20%20%20%20labels%3A%20%5B2012%2C%202013%2C%202014%2C%202015%2C%202016%5D%2C%5Cn%20%20%20%20datasets%3A%20%5B%7B%5Cn%20%20%20%20%20%20label%3A%20'Gradient%20example'%2C%5Cn%20%20%20%20%20%20data%3A%20%5B12%2C%206%2C%205%2C%2018%5D%2C%5Cn%20%20%20%20%20%20backgroundColor%3A%20getGradientFillHelper('vertical'%2C%20%5B%5C%22%2336a2eb%5C%22%2C%20%5C%22%23a336eb%5C%22%2C%20%5C%22%23eb3639%5C%22%5D)%2C%5Cn%20%20%20%20%7D%5D%5Cn%20%20%7D%5Cn%7D%22%2C%22width%22%3A500%2C%22height%22%3A300%2C%22version%22%3A%222.9.4%22%7D) taken from the [gradient docs](https://quickchart.io/documentation/reference/colors-and-backgrounds/#gradient-fills), shows the issue when changing the chart version from 2 to 3.

**Comment by typpo** [comment]
Hi @cworsley4,

Thank you for flagging this.  The issue has been resolved.  It had to do with a change that attempted to make sandboxing more efficient on the server side.

Note that some previously generated images may be cached, but you can always force a new image by adding a cache-busting string to the URL, e.g. `&t=<current timestamp>`

[Link to Chart.js v3 example](https://quickchart.io/sandbox/#%7B%22chart%22%3A%22%7B%5Cn%20%20type%3A%20'bar'%2C%5Cn%20%20data%3A%20%7B%5Cn%20%20%20%20labels%3A%20%5B'Q1'%5D%2C%5Cn%20%20%20%20datasets%3A%20%5B%5Cn%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20label%3A%20'Users'%2C%5Cn%20%20%20%20%20%20%20%20data%3A%20%5B75%5D%2C%5Cn%20%20%20%20%20%20%20%20backgroundColor%3A%20getGradientFillHelper('horizontal'%2C%20%5B%5Cn%20%20%20%20%20%20%20%20%20%20'green'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'yellow'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'orange'%2C%5Cn%20%20%20%20%20%20%20%20%20%20'red'%2C%5Cn%20%20%20%20%20%20%20%20%5D)%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%5D%2C%5Cn%20%20%7D%2C%5Cn%20%20options%3A%20%7B%5Cn%20%20%20%20indexAxis%3A%20'y'%2C%5Cn%20%20%20%20layout%3A%20%7B%5Cn%20%20%20%20%20%20padding%3A%2040%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20scales%3A%20%7B%5Cn%20%20%20%20%20%20x%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20y%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20plugins%3A%20%7B%5Cn%20%20%20%20%20%20legend%3A%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20false%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20annotation%3A%20%7B%5Cn%20%20%20%20%20%20%20%20clip%3A%20false%2C%5Cn%20%20%20%20%20%20%20%20common%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20drawTime%3A%20'afterDraw'%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20annotations%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20low%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%204%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Low'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20medium%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2050%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Medium'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20high%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2095%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'High'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20arrow%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'point'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20pointStyle%3A%20'triangle'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20'%23000'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20radius%3A%2015%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2075%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yAdjust%3A%2065%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20label1%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20'label'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20xValue%3A%2075%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20yAdjust%3A%2095%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20%5B'Your%20score'%2C%20'75%25'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20font%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20size%3A%2018%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20weight%3A%20'bold'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%7D%2C%5Cn%20%20%7D%2C%5Cn%7D%22%2C%22width%22%3A500%2C%22height%22%3A150%2C%22version%22%3A%223%22%2C%22backgroundColor%22%3A%22%23fff%22%7D)

**Comment by cworsley4** [comment]
@typpo thank you for the quick resolution. I checked and all looks well to me :) Cheers.
