### ISSUE TITLE
How to install quickchart locally

### ISSUE THREAD

**Issue by frizquierdo** [typpo/quickchart#162]
Hi, someone can help me to install quickchart locally in Debian host, not docker image!!! I need it run on http://localhost:3005 url for example. Thank you.

**Comment by typpo** [comment]
Hi @frizquierdo,

See the section on running the server: https://github.com/typpo/quickchart#running-the-server

It is a Node app written in Javascript, so you can run it locally by cloning the repository and running `node index.js`.  Make sure you have at least Node 12 installed.
