### ISSUE TITLE
Support for big numbers with delimiter 

### ISSUE THREAD

**Issue by Pryla** [typpo/quickchart#17]
Great work! I am using your chart images for a project, where users generate huge numbers between 100k and 100Mio. Those numbers just look awful inside any chart or on the y-axis. Do you have a non js-solution for this issue? Because the images are provided within an email so there is no js-support given.

**Comment by typpo** [comment]
Hi @Pryla,

Thanks for the feedback!  Can you be more specific about what a solution would look like?

One option is set the labels on the graph with suffixes, e.g. 100k or 100M.  The best way to do this is by using the `ticks.callback` option provided by the Chart.js API: https://stackoverflow.com/questions/51108964/shorten-number-labels-in-charts-js

Here's a full example:

```
{
  type: 'bar',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [{
      label: 'Count',
      data: [ 5000000, 6000000, 70000000, 1000080, 19000000 ]
    }]
  },
  options: {
    scales: {
      yAxes: [{
        ticks: {
          callback: function(value, index, values) {
            return value / 1e6 + 'M';
          }
        }
      }]
    }
  }
}
```

[Link](https://quickchart.io/chart?bkg=white&c=%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%27January%27%2C%20%27February%27%2C%20%27March%27%2C%20%27April%27%2C%20%27May%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20label%3A%20%27Count%27%2C%0A%20%20%20%20%20%20data%3A%20%5B%205000000%2C%206000000%2C%2070000000%2C%201000080%2C%2019000000%20%5D%0A%20%20%20%20%7D%5D%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20scales%3A%20%7B%0A%20%20%20%20%20%20yAxes%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20ticks%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20callback%3A%20function(value%2C%20index%2C%20values)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20value%20%2F%201e6%20%2B%20%27M%27%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

![image](https://user-images.githubusercontent.com/310310/62085572-c7093100-b210-11e9-8b0e-56d1c4441a99.png)

**Comment by Pryla** [comment]
Hi @typpo 
thank you for sharing this link I just did not find it before.

My problem is the callback function which always produces the unexpected string error. 

My code looks like this:

```
<img src="https://quickchart.io/chart?width=500&height=300&c={
type:'line',
 data:{
 labels:['2016','2017','2018','2019'],
  datasets:[{
   label:'Umsatz',
   backgroundColor:'rgb(240,125,0)',
   data:[10,20,30,40]
  }]
 },
options:{
 scales:{
  yAxes:[{
   ticks:{
     callback:function(value,index,values){
        <?php echo "return value / 1e6 +'M';" ?>
       // or
       return value / 1e6 + 'M';
     }
    }
   }]
  }
 }
}
">

```

Is there a chance to get this to work? Thank you! In my case I will generate this while sending an email.

Thank you for your help! It is much appreciated!

**Comment by typpo** [comment]
I'm not sure what you're trying to do here.  The `callback` function is just a label formatter, so you should not be putting PHP code in it.  Your server should output values in the `datasets.data` array.

**Comment by Pryla** [comment]
I figured out that the 
`return value / 1e6 + 'M';`

was causing the unexpected string error with the 'M'. So I just removed it and put it into the label. I don't know why the error was thrown because in this example or the realtime editor it works just fine.

Thanks anyways.
