### ISSUE TITLE
Unique tags for inline SVG

### ISSUE THREAD

**Issue by dcolazin** [typpo/quickchart#179]
Currently, two inline svg produced by quickchart might be rendered wrongly, as they share the clip tag ids (and maybe even other ids in certain cases?). This issue can be fixed client-side (for example with [this hack](https://blog.jim-nielsen.com/2022/multiple-inline-svgs/) or with more proper svg manipulation) having a counter to be appended on the tag id. In this way, all svg will have different tag ids.

Yet, I believe this issue should be fixed server-side, as quickchart should produce svg that are ready to be used, and multiple inline svg are common. To mitigate the id collision, even in distributed settings, a suitable length hash or random string should be generated for each svg and appended to the tag ids. Moreover, it should be possible to accept a tag id parameter from the client to be used instead of the generated hash/random string.

**Comment by typpo** [comment]
Thanks for flagging this.  I'm happy to add a random string to each ID using the hack that you linked.  The structure of the SVG is relatively stable so it should be ok.

**Comment by dcolazin** [comment]
Thank you!
