### ISSUE TITLE
Base64 Data

### ISSUE THREAD

**Issue by Cretezy** [typpo/quickchart#21]
It would be nice to support base64 for the data, hence avoiding multiple problems of having to deal with encoding JSON in the URL.

**Comment by typpo** [comment]
That's a good idea, I'll see what I can do.  In the meantime, do you want to share your difficulty URL-encoding the JSON?  I would imagine base64 encoding is no more difficult than URL encoding, as most languages have built-in libraries capable of doing both.

**Comment by Cretezy** [comment]
It could help with handling of the pound symbol for sure, it's a lot more trouble to have to convert hex -> rgb than just base64 it :yum:

**Comment by typpo** [comment]
Hmm, I think your URL encoder should handle pound signs though!  For example, in Javascript:

```
> encodeURIComponent('color:#abc123')
'color%3A%23abc123'
```

**Comment by typpo** [comment]
Goods news, I've just added support for base64 encoding!  Although you could theoretically solve your problem with URL encoding, base64 is more compact and it plays nicer with unicode :)

Here's an example:

https://quickchart.io/chart?encoding=base64&c=ew0KICB0eXBlOiAnYmFyJywNCiAgZGF0YTogew0KICAgIGxhYmVsczogWydKYW51YXJ5JywgJ0ZlYnJ1YXJ5JywgJ01hcmNoJywgJ0FwcmlsJywgJ01heSddLA0KICAgIGRhdGFzZXRzOiBbew0KICAgICAgbGFiZWw6ICdEb2dzJywNCiAgICAgIGRhdGE6IFsgNTAsIDYwLCA3MCwgMTgwLCAxOTAgXQ0KICAgIH0sIHsNCiAgICAgIGxhYmVsOiAnQ2F0cycsDQogICAgICBkYXRhOiBbIDEwMCwgMjAwLCAzMDAsIDQwMCwgNTAwIF0NCiAgICB9XQ0KICB9DQp9

![image](https://user-images.githubusercontent.com/310310/63469184-73a88e00-c41e-11e9-8de2-4c64ad1f68a1.png)

Docker package is updated as well.  Let me know if you have any issues!

**Comment by Cretezy** [comment]
Ah you're totally right about `#`! The README slightly confused me.

Anyways thanks, this is an awesome feature!
