### ISSUE TITLE
Expensive health-check

### ISSUE THREAD

**Issue by mcobzarenco** [typpo/quickchart#24]
I was curious if there's a reason the newly added `/healthcheck` route generates random data and actually creates a chart? It seems a bit too expensive for a healthcheck -- though it does test whether the chart generation works; To run this in k8s I just need a simple healthcheck route that is super cheap to evaluate (such as returning `200 OK` without any work).

**Comment by mcobzarenco** [comment]
Happy to change the current health-check and submit a PR unless there's a good reason why it's expensive. Thanks!

**Comment by typpo** [comment]
Hi Marius, thanks for the feedback. The reasons why I created an endpoint that actually renders a chart:

1. The service runs behind Cloudflare and I wanted a healthcheck that could not be cached (hence the random chart)

2.  I wanted the health check to ensure that chart rendering was working properly.  I was worried about some state (e.g. high CPU usage) in which the server might be responsive but chart rendering was slowed.

To save you some trouble, I've changed `/healthcheck` to be lightweight and moved the previous "random chart" endpoint to `/healthcheck/chart`, so it should now be good for your purposes!

Planning to update the README with more info on health and monitoring...

**Comment by mcobzarenco** [comment]
Wow, @typpo that was quick! Makes a lot of sense, thanks.

**Comment by mcobzarenco** [comment]
Also -- just wanted to say -- really useful library!

**Comment by typpo** [comment]
Thanks!  Just a heads up, the public Docker build is not updated automatically.  That will be done shortly in case you are using it.
