### ISSUE TITLE
lineTension option has no effect

### ISSUE THREAD

**Issue by adityapatadia** [typpo/quickchart#32]
We tried to create chart but the chart always draws straight line. Bezier curve does not come in chart.

```

{
  type: 'line',
  data: {
    labels: ['1:00', '2:00', '3:00', '4:00', '5:00', '1:00', '2:00', '3:00', '4:00', '5:00', '1:00', '2:00', '3:00', '4:00', '5:00'],
    datasets: [{
      lineTension: 0.4,
      label: 'Dogs',
      backgroundColor: 'purple',
      borderColor: 'purple',
      data: [ 50, 60, 70, 180, 190 ,50, 60, 70, 180, 190,50, 60, 70, 180, 190],
      fill: false,
    }]
  },
  options: {
    title: {
      display: true,
      text: 'Total Revenue (billions)',
      fontColor: 'black',
      fontSize: 20,
    },
    legend: {
      position: 'bottom',
    }
  }   
}

```

**Comment by typpo** [comment]
Hi Aditya,

Are you using QuickChart.io or self hosting?  The following URL shows a chart with curved lines and adjusting `lineTension` alters the graph accordingly.  I just copied your config and pasted it in:

https://quickchart.io/chart?bkg=white&c=%7B%0A%20%20type%3A%20%27line%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%271%3A00%27%2C%20%272%3A00%27%2C%20%273%3A00%27%2C%20%274%3A00%27%2C%20%275%3A00%27%2C%20%271%3A00%27%2C%20%272%3A00%27%2C%20%273%3A00%27%2C%20%274%3A00%27%2C%20%275%3A00%27%2C%20%271%3A00%27%2C%20%272%3A00%27%2C%20%273%3A00%27%2C%20%274%3A00%27%2C%20%275%3A00%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20lineTension%3A%200.4%2C%0A%20%20%20%20%20%20label%3A%20%27Dogs%27%2C%0A%20%20%20%20%20%20backgroundColor%3A%20%27purple%27%2C%0A%20%20%20%20%20%20borderColor%3A%20%27purple%27%2C%0A%20%20%20%20%20%20data%3A%20%5B%2050%2C%2060%2C%2070%2C%20180%2C%20190%20%2C50%2C%2060%2C%2070%2C%20180%2C%20190%2C50%2C%2060%2C%2070%2C%20180%2C%20190%5D%2C%0A%20%20%20%20%20%20fill%3A%20false%2C%0A%20%20%20%20%7D%5D%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20title%3A%20%7B%0A%20%20%20%20%20%20display%3A%20true%2C%0A%20%20%20%20%20%20text%3A%20%27Total%20Revenue%20(billions)%27%2C%0A%20%20%20%20%20%20fontColor%3A%20%27black%27%2C%0A%20%20%20%20%20%20fontSize%3A%2020%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20legend%3A%20%7B%0A%20%20%20%20%20%20position%3A%20%27bottom%27%2C%0A%20%20%20%20%7D%0A%20%20%7D%20%20%20%0A%7D

![image](https://user-images.githubusercontent.com/310310/68742210-742b6d80-05a4-11ea-9a0f-1a4b66ee1ae1.png)

**Comment by adityapatadia** [comment]
Weird. Just putting quotes around `0.4` solved the issue.
