### ISSUE TITLE
Line Chart without shading

### ISSUE THREAD

**Issue by GrahamJohnWhite** [typpo/quickchart#33]
Hi,

I am new to this but have managed to create a line chart with the code below, however, when it creates the chart there is shading from the lien to the x-axes.  I don't want any shading at all just the lines.  How do I achieve this?

<img src="https://quickchart.io/chart?c={type:'line',data:{labels:['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21'], datasets:[{label:'Target',data:[28152,56304,84456,140760,197064,225216,253368,281520,309672,337824,365976,394128,422280,450432,478584,506736,534888,563040,591192]},{label:'Actual',data:[26657,48757,82028,159596,185229,216206,243242,275549,310121,336515,364990,386965,432594]},{label:'Last Year',data:[27806,55612,83418,111224,139030,166836,194642,222448,250254,278060,305866,333672,361478,389284,417090,444896,472702,500508,528314,556120,583926]}]},options:{title: {display: true,text: 'MTD Commission'}}}">

**Comment by typpo** [comment]
Hey @GrahamJohnWhite, could you please paste the chart config again?  It looks like it didn't paste correctly in the original.

**Comment by GrahamJohnWhite** [comment]
chart?c={type:'line',data:{labels:['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21'], datasets:[{label:'Target',data:[28152,56304,84456,140760,197064,225216,253368,281520,309672,337824,365976,394128,422280,450432,478584,506736,534888,563040,591192]},{label:'Actual',data:[26657,48757,82028,159596,185229,216206,243242,275549,310121,336515,364990,386965,432594]},{label:'Last Year',data:[27806,55612,83418,111224,139030,166836,194642,222448,250254,278060,305866,333672,361478,389284,417090,444896,472702,500508,528314,556120,583926]}]},options:{title: {display: true,text: 'MTD Commission'}}}

**Comment by typpo** [comment]
This question is actually about Chart.js, not QuickChart.  Per the [Chart.js documentation](https://www.chartjs.org/docs/latest/charts/line.html) you can set `fill: false` for each dataset.

![image](https://user-images.githubusercontent.com/310310/69289696-39cc5c80-0bb2-11ea-9e4e-69ee22aebf4b.png)

```
{
  "type": "line",
  "data": {
    "labels": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21"
    ],
    "datasets": [
      {
        "label": "Target",
        "fill": false,
        "data": [
          28152,
          56304,
          84456,
          140760,
          197064,
          225216,
          253368,
          281520,
          309672,
          337824,
          365976,
          394128,
          422280,
          450432,
          478584,
          506736,
          534888,
          563040,
          591192
        ]
      },
      {
        "label": "Actual",
        "fill": false,
        "data": [
          26657,
          48757,
          82028,
          159596,
          185229,
          216206,
          243242,
          275549,
          310121,
          336515,
          364990,
          386965,
          432594
        ]
      },
      {
        "label": "Last Year",
        "fill": false,
        "data": [
          27806,
          55612,
          83418,
          111224,
          139030,
          166836,
          194642,
          222448,
          250254,
          278060,
          305866,
          333672,
          361478,
          389284,
          417090,
          444896,
          472702,
          500508,
          528314,
          556120,
          583926
        ]
      }
    ]
  },
  "options": {
    "title": {
      "display": true,
      "text": "MTD Commission"
    }
  }
}
```
