### ISSUE TITLE
passing js to ticks callback dont work

### ISSUE THREAD

**Issue by DaniilLysenko** [typpo/quickchart#35]
"ticks": {
                    "beginAtZero": true,
                    "fontSize": 8,
                    "fontColor": "#8192E8",
                    "callback": "function(label){return label + 'h';}"
                }

**Comment by DaniilLysenko** [comment]
Chart Error: function(label) {return label + 'h';} is not a function

**Comment by typpo** [comment]
Chart.js config requires that you pass it as an actual function, not a string:

```
"ticks": {
                "beginAtZero": true,
                "fontSize": 8,
                "fontColor": "#8192E8",
                "callback": function(label){return label + 'h';}
            }
```

**Comment by DaniilLysenko** [comment]
But how I pass it to json?

**Comment by typpo** [comment]
You should send the _entire_ config parameter as a string:

```
"chart": "\"ticks\": { \"beginAtZero\": true, ..., \"callback\": function(label) {return label + 'h';}}"
```

For a Chart containing Javascript, the POST schema is like so:

```
interface Params {
  backgroundColor?: string
  width?: number,
  height?: number,
  devicePixelRatio?: number,
  format?: "png" | "pdf",
  chart: string,
}
```
