### ISSUE TITLE
Can't set `margin=0` query for `qr` endpoint

### ISSUE THREAD

**Issue by sntran** [typpo/quickchart#37]
## Steps to reproduce

Use this URL:

`https://quickchart.io/qr?text=Bug&margin=0`

## Expected

An QR Code with no whitespace around it.

## Actual

An QR Code with margin of "4".

![QR Code with margin 0](https://quickchart.io/qr?text=Bug&margin=0)

**Comment by typpo** [comment]
Thanks for catching this.  I've pushed a fix.

https://quickchart.io/qr?text=Bug2&margin=0

![image](https://user-images.githubusercontent.com/310310/70728490-5aba3600-1cb6-11ea-8bf4-c34e1e43f72a.png)

Unfortunately the QR codes are cached, so the codes that have already been generated will continue to appear for some time on quickchart.io.  If you generate a new URL, the codes with margin=0 will display correctly.
