### ISSUE TITLE
Can't set `format=svg` for `qr` endpoint

### ISSUE THREAD

**Issue by sntran** [typpo/quickchart#38]
## Steps to Reproduce

Use this URL:

`https://quickchart.io/qr?text=Bug&format=svg`

## Expected:

An QR code in SVG format

## Actual

A broken QR Code

![QR Code SVG](https://quickchart.io/qr?text=Bug&format=svg)

**Comment by typpo** [comment]
Thanks for catching this.  The SVG was mistakenly being written as a literal QR code.  Similar to #37, existing QR codes are cached for some time so you may have to generate new unique QR codes or hard refresh your browser.

https://quickchart.io/qr?text=Bug2&format=svg

I've also improved the test so it verifies the part of the contents of the SVG.
