### ISSUE TITLE
request: sparkline as a style

### ISSUE THREAD

**Issue by randallt** [typpo/quickchart#4]
Trying to get a clean sparkline out of this is a real chore. Consider a new chart style of 'sparkline' that can take a dataset and by default show just the line (no axes, no filll, etc).

**Comment by typpo** [comment]
Done.  The `sparkline` type has been added by `f760d85` and QuickChart.io is updated.  

The sparkline is a line chart with the following option defaults:

```
"options":{  
      "legend":{  
         "display":false
      },
      "elements":{  
         "line":{  
            "borderColor":"#000",
            "borderWidth":1
         },
         "point":{  
            "radius":0
         }
      },
      "scales":{  
         "yAxes":[  
            {  
               "display":false
            }
         ],
         "xAxes":[  
            {  
               "display":false
            }
         ]
      },
```
Also, labels are automatically `null`ed and dataset `linetension` is set to 0.

Here's an example:

[https://quickchart.io/chart?c={type:'sparkline',data:{datasets:[{data:[140,60,274,370,199]}]}}](https://quickchart.io/chart?c={type:'sparkline',data:{datasets:[{data:[140,60,274,370,199]}]}})
![image](https://user-images.githubusercontent.com/310310/54941837-0b936180-4eeb-11e9-9f0f-5a6a48c375f4.png)

**Comment by randallt** [comment]
Awesome. How would I disable the fill?

**Comment by typpo** [comment]
According to the [Chart.js documentation](https://www.chartjs.org/docs/latest/charts/line.html), set the `dataset` property `fill` to false.  For example:

```
{
   type:'sparkline',
   data:{
      datasets:[
         {
            data:[50, 60, 70, 180, 190],
            fill: false,
         }
      ]
   }
}
```
