### ISSUE TITLE
Request for adding background colors

### ISSUE THREAD

**Issue by mxrch** [typpo/quickchart#40]
Hey, I'm developing a Discord bot in Python, and for a command I generate a chart. I'm currently using plotly but it takes 30 secondes to generate it.
I find quickchart so useful, but the only problem is that I can't find how to set a background color, like a dark background.
So I was wondering if it was possible to add it in quickchart ?
Thanks in advance !

**Comment by typpo** [comment]
Hi @mxrch, fortunately there is already a way to specify background color!  You can do this using the `backgroundColor` or `bkg` parameter.

You can set the value to RGB (e.g. `rgb(255,255,120)`) or a color (e.g. `pink`).  If you set a value to hex, you must URL encode the hash sign (e.g. `%23ff00ff`).

Here's an example:

https://quickchart.io/chart?bkg=rgb(255,255,120)&c={type:%20%27bar%27,data:%20{labels:%20[2012,%202013,%202014,%202015,%202016],datasets:%20[{%20%20label:%20%27Raisins%27,%20%20data:%20[12,%206,%205,%2018,%2012]},%20{%20%20label:%20%27Bananas%27,%20%20data:%20[4,%208,%2016,%205,%205]}]}}

![image](https://user-images.githubusercontent.com/310310/73323005-ddfa0180-41fa-11ea-8ba4-4854d6c5e37e.png)

**Comment by mxrch** [comment]
Oh, perfect ! So I misread the documentation, sorry.
Thank you so much ! 😄

**Comment by typpo** [comment]
Updated the documentation with `backgroundColor` example in 72d50b08393d61a47e06dcd9a59783b2262e0eea

Thanks!
