### ISSUE TITLE
Url shortener throws cloud fare errors. 

### ISSUE THREAD

**Issue by jaredgib** [typpo/quickchart#41]
I am using this code i got from an admin at quickchart as an example of what to include in the api body for a chart url to be shortened. 

{“chart”: {“type”: “bar”, “data”: {“labels”: [“Hello”, “World”], “datasets”: [{“label”: “Foo”, “data”: [1, 2]}]}}}

The above works just fine but for some reason the code below does not.  Do I have improper syntax?

{“chart”:{“type”: “line”, “data”: {“labels”: [“jan 1”,“jan 2”, “jan 3”], “datasets”: [{“label”: “cow”,“data”: [4,5,6], “fill”: “false”, “borderColor”:“red”}]},“options”: {“title”: {“display”: “true”, “text”: “Daily Behavioral Occurrence vs Non-Occurrence”}, “scales”: {“yAxes”: [{“scaleLabel”: {“display”: “true”, “labelString”:“Non-Occurrence / Occurrence”}, “ticks”:{“reverse”: “false”, “stepSize”:1}}]},},}}

the code from above does produce a chart in the live editor on the quickchart website but when i send the API POST demand i get the weird cloudfare message again. (To produce the chart on the website remove {“chart”:}

**Comment by typpo** [comment]
Hey @jaredgib, yes, the second example is not valid JSON.  You should either clean it up so it's valid JSON or send the entire `{"type" ... }` object as a string.  The sandbox editor works for this example because it sends the input as a string and the server uses a relaxed JSON parser.  However Cloudflare's JSON parser is strict.

Here is the type spec of the POST object:
```
 interface PostData {
    backgroundColor: string,
    width: number;
    height: number;
    format: "png" | "pdf";
    chart: string | object;
  }
```

**Comment by jaredgib** [comment]
{ 
   "chart":{ 
      "type":"line",
      "data":{ 
         "labels":[ 
            “jan 1”,
            “jan 2”,
            “jan 3”
         ],
         "datasets":[ 
            { 
               "label":"cow",
               "data":[ 
                  4,
                  5,
                  6
               ],
               "fill":"false",
               "borderColor":"red"
            }
         ]
      },
      "options":{ 
         "title":{ 
            "display":"true",
            "text":"Daily Behavioral Occurrence vs Non-Occurrence"
         },
         "scales":{ 
            "yAxes":[ 
               { 
                  "scaleLabel":{ 
                     "display":"true",
                     "labelString":"Non-Occurrence / Occurrence"
                  },
                  "ticks":{ 
                     "reverse":"false",
                     "stepSize":1
                  }
               }
            ]
         }
      }
   }
}

I am trying to wrap my head around the Json. Does that look better?

Could you provide an example of what a request would look like in string format? I’m new to this stuff and would appreciate any examples that or guidance!

**Comment by typpo** [comment]
You can use a JSON linter to be absolutely sure your JSON is well-formed (e.g. https://jsonlint.com)

In this case, looks like your quotes around labels are fancy quotes instead of double quotes.  The visual difference is hard to spot, but of course computers don't care.  Valid JSON would be:

```
"labels": ["jan 1", "jan 2", "jan 3"],
```

**Comment by jaredgib** [comment]
Dude. You rock. Thanks so much. This works!

**Comment by typpo** [comment]
Awesome, glad you are up and running!
