### ISSUE TITLE
Trend lines are a missing feature

### ISSUE THREAD

**Issue by ghost** [typpo/quickchart#42]
Trend lines are vital for visual analysis of many types of line and scatter plot graphs. To my knowledge, adding this capacity is possible. What do you guys think? Will it work with the system?

**Comment by jaredgib** [comment]
https://github.com/Makanz/chartjs-plugin-trendline#readme

Here is one plugin currently available.

**Comment by typpo** [comment]
Update on this.  I gave it a quick try but it looks like it's an older-style plugin that relies on a global Chart object.  Due to how it's built I'm wary of adding it to every bar and line graph render.  I might fork it/update the library if there is more demand for this feature.

**Comment by jaredgib** [comment]
Understood, thank you for trying though!!! I still love the service!

Time to figure out how to set it on my own virtual server 🤣🤣 🤯
