### ISSUE TITLE
Returning undefined

### ISSUE THREAD

**Issue by jaredgib** [typpo/quickchart#46]
I am trying to pass this through the HTML request. I am only getting errors back. This does work in the editor as seen here. 
![image](https://user-images.githubusercontent.com/58823942/75085102-ceb55d80-54f3-11ea-897e-cae91db9887b.png)

This returns "unexpected string" but I am not sure where I am going wrong. When use the editor on the the main quickchart page, and click on the provided link, this works just fine. What am i doing incorrectly here?

{
  type: 'line',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [
{
      	label: 'Corrects',
      	data: [ 10, 60, 70, 180, 190 ], 
	fill: false,
	borderColor:'green'}, 
{
    	  label: 'Incorrects',
     	 data: [ .10, 20, 30, 40, 50 ], 
	fill: false, 
	borderColor: 'purple'
    }]
  },
  options: {
    	title: {
     	 display: true,
      	text: 'SAFMEDS',
      	fontColor: 'blue',
      	fontSize: 32,
    },
    	legend: {
      	position: 'bottom',
    },
    	scales: {
      
      	yAxes: [{ type: 'logarithmic', 
        
        	ticks: {
        	autoSkip: false,
        	min:.001, max: 1000,callback: function (value, index, values) {if( value==.001 || value==.01 || value==.1 || value==1 || value==10 || value==100 || value==1000){return value + ' per minute';}},}}],},},}

**Comment by jaredgib** [comment]
{
  type: 'line',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [
{
      	label: 'Corrects',
      	data: [ 10, 60, 70, 180, 190 ], 
	fill: false,
	borderColor:'green'}, 
{
    	  label: 'Incorrects',
     	 data: [ .10, 20, 30, 40, 50 ], 
	fill: false, 
	borderColor: 'purple'
    }]
  },
  options: {
    	title: {
     	 display: true,
      	text: 'SAFMEDS',
      	fontColor: 'blue',
      	fontSize: 32,
    },
    	legend: {
      	position: 'bottom',
    },
    	scales: {
      
      	yAxes: [{ type: 'logarithmic', 
        
        	ticks: {
        	autoSkip: false,
        	min:.001, max: 1000,callback: function (value, index, values) {if( value==.001 || value==.01 || value==.1 || value==1 || value==10 || value==100 || value==1000){return value + ' per minute';}},}}],},},}

**Comment by typpo** [comment]
If it works in the live editor, it means there's nothing wrong with the config but you're probably not encoding it properly in your program's request to QuickChart.  I wouldn't be able to help here unless you shared the entire request that is being sent.

**Comment by jaredgib** [comment]
that makes sense. Here you go, my full request. 


https://quickchart.io/chart?bkg=white&c={type: 'line',
data: {
labels: ['January', 'February', 'March', 'April', 'May'],
datasets: [
{
label: 'Corrects',
data: [ 10, 60, 70, 180, 190 ],
fill: false,
borderColor:'green'},
{
label: 'Incorrects',
data: [ .10, 20, 30, 40, 50 ],
fill: false,
borderColor: 'purple'
}]
},
options: {
title: {
display: true,
text: 'SAFMEDS',
fontColor: 'blue',
fontSize: 32,
},
legend: {
position: 'bottom',
},
scales: {

  	yAxes: [{ type: 'logarithmic', 
    
    	ticks: {
    	autoSkip: false,
    	min:.001, max: 1000,callback: function (value, index, values) {if( value==.001 || value==.01 || value==.1 || value==1 || value==10 || value==100 || value==1000){return value + ' per minute';}},}}],},},}





when i click through the link provided in the editor, the url displayed is this: 
https://quickchart.io/chart?bkg=white&c=%7B%0Atype%3A%20%27line%27%2C%0Adata%3A%20%7B%0Alabels%3A%20%5B%27January%27%2C%20%27February%27%2C%20%27March%27%2C%20%27April%27%2C%20%27May%27%5D%2C%0Adatasets%3A%20%5B%0A%7B%0Alabel%3A%20%27Corrects%27%2C%0Adata%3A%20%5B%2010%2C%2060%2C%2070%2C%20180%2C%20190%20%5D%2C%0Afill%3A%20false%2C%0AborderColor%3A%27green%27%7D%2C%0A%7B%0Alabel%3A%20%27Incorrects%27%2C%0Adata%3A%20%5B%20.10%2C%2020%2C%2030%2C%2040%2C%2050%20%5D%2C%0Afill%3A%20false%2C%0AborderColor%3A%20%27purple%27%0A%7D%5D%0A%7D%2C%0Aoptions%3A%20%7B%0Atitle%3A%20%7B%0Adisplay%3A%20true%2C%0Atext%3A%20%27SAFMEDS%27%2C%0AfontColor%3A%20%27blue%27%2C%0AfontSize%3A%2032%2C%0A%7D%2C%0Alegend%3A%20%7B%0Aposition%3A%20%27bottom%27%2C%0A%7D%2C%0Ascales%3A%20%7B%0A%0A%20%20%09yAxes%3A%20%5B%7B%20type%3A%20%27logarithmic%27%2C%20%0A%20%20%20%20%0A%20%20%20%20%09ticks%3A%20%7B%0A%20%20%20%20%09autoSkip%3A%20false%2C%0A%20%20%20%20%09min%3A.001%2C%20max%3A%201000%2Ccallback%3A%20function%20(value%2C%20index%2C%20values)%20%7Bif(%20value%3D%3D.001%20%7C%7C%20value%3D%3D.01%20%7C%7C%20value%3D%3D.1%20%7C%7C%20value%3D%3D1%20%7C%7C%20value%3D%3D10%20%7C%7C%20value%3D%3D100%20%7C%7C%20value%3D%3D1000)%7Breturn%20value%20%2B%20%27%20per%20minute%27%3B%7D%7D%2C%7D%7D%5D%2C%7D%2C%7D%2C%7D

**Comment by typpo** [comment]
You have to make sure to URL encode your request (or base 64 encode if you prefer - see [documentation](https://quickchart.io/documentation#parameters)).  Most programming languages have a way to do this, or you can use a URL encoder online such as https://www.urlencoder.io

**Comment by jaredgib** [comment]
On it! I’ll report back

**Comment by jaredgib** [comment]
So, I'm having trouble effectively encoding this. Are you aware which characters aren't passing successfully? I ask because, for every other chart that I don't include some kind of callback function, this doesn't need to occur. Is it every character of the chart description?

For now I will try using your post method to retrive the picture. You state that to format labels and use the POST method, I need to pass things as a string. Can you provide a brief example fo what my chart parameters might look like?

**Comment by typpo** [comment]
Hey @jaredgib, usually the best way to encode a URL is to use your language's built-in URL encoding feature as you really should be encoding the whole thing.  Most non-letters or numbers are URL encoded.

A POST payload with a string might look like this:

```
  {
    "backgroundColor": "transparent",
    "width": 500,
    "height": 300,
    "format": "png",
    "chart": '{"type": "bar", "data": {"labels": ["Hello", "World"], "datasets": [{"label": "Foo", "data": [1, 2]}]}}',
  }
```

(note the single quotes around the "chart" value)

Hope this helps!

**Comment by jaredgib** [comment]
Thank you! I will work on this and get back to you if I figure it out. I am
on the ThunkableX app builder platform. When using their built in
“webviewer” my url example works. But for UI reasons I must use it as a
image component source url which does not encode. I will reach out to them
for a fix. In the meantime I will try and make a POST as you’ve shown
below. Thank you for your time. I appreciate it bunches!

Here is what I’ve settled with for now

Pop

**Comment by typpo** [comment]
Ah, it does sound like it's a problem with Thunkable.  Seems like some of their components automatically URL encode, some don't.  [This Thunkable community thread](https://community.thunkable.com/t/method-to-use-bit-ly-url-shortener-service/17516) describes a `UriEncode` method in the Web component - maybe that helps?  Otherwise, you can do it manually (as pictured in the original post) but that's ugly and potentially incomplete.

The POST approach may be easier for you - just need to convert the JSON you're already building into a string.

**Comment by jaredgib** [comment]
I got it!!!![
<img width="841" alt="Screen Shot 2020-02-24 at 11 46 43 AM" src="https://user-images.githubusercontent.com/58823942/75207987-44b20280-5748-11ea-8f89-7e992a05a050.png">
](url)

**Comment by typpo** [comment]
That's great to hear!  Thanks for sharing the solution :smile:
