### ISSUE TITLE
Height and width not being respected by POST

### ISSUE THREAD

**Issue by prettycode** [typpo/quickchart#48]
Greetings!

I've recently been trying the quickchart.io service in order to evaluate whether our company would like to use a paid tier. What we're trying to do is make POST requests for chart images and get back HTTP responses of the PNG images (vs. getting back a link to a short URL or making HTTP GET requests with the chart settings/configuration in the URL).

For example, we're sending the following request to the endpoint `https://quickchart.io/chart` in a POST:

```
{
  "chart": {
    "type": "horizontalBar",
    "data": {
      "labels": [
        "1+ yr",
        "1 - 12 months",
        "1 - 4 weeks",
        "< 1 week"
      ],
      "datasets": [
        {
          "label": "Participants",
          "data": [
            12,
            2,
            8,
            24
          ]
        }
      ]
    }
  },
  "height": 200,
  "width": 300,
  "format": "png"
}
```

What we get back is an image that is 400 pixels in height and 600 pixels in width.

I've tried adding numerous options to the `chart` object and still no luck. What I've tried, for example, is setting these properties on `chart.options`:

* `aspectRatio: 1`
* `responsive` both true and false
* `maintainAspectRatio` both true and false

None of these options seem to affect the output image—it still always ends up being 2x the size that I send for `height` and `width`.

A workaround I tried is to simply send a `height` and `width` value that is half of what I actually want. When I do that, the PNG that comes back is the correct size, but the labels seem disproportionately large. 

We've had to resort to not using the aforementioned workaround and post-processing the image ourselves—we read it into a library and perform a scaling/resizing operation on it to reduce dimensions by half.

Am I missing or misunderstanding something? How can I request and image that is X pixels in width and Y pixels in height and get back an image that is exactly those dimensions?

Thanks so much!

**Comment by typpo** [comment]
Hi Chris,

Try setting `devicePixelRatio` to `1.0`.  It is 2.0 by default for retina support, which causes the true dimensions of your image to be 2x width and height.  I know it's confusing but unfortunately I can't change it for backwards compatibility reasons :( 

Your postData would look like this:

```
{
  "devicePixelRatio": 1.0,
  "chart": {
    "type": "horizontalBar",
    "data": {
      "labels": [
        "1+ yr",
        "1 - 12 months",
        "1 - 4 weeks",
        "< 1 week"
      ],
      "datasets": [
        {
          "label": "Participants",
          "data": [
            12,
            2,
            8,
            24
          ]
        }
      ]
    }
  },
  "height": 200,
  "width": 300,
  "format": "png"
}
```

**Comment by prettycode** [comment]
Ah, beautiful, works like a charm. Much appreciated, Ian!
