### ISSUE TITLE
Tooltip not working in email

### ISSUE THREAD

**Issue by imanagemyschool** [typpo/quickchart#51]
I am trying to get the tooltip by using this API => https://quickchart.io/chart?width=700&height=300&c=<data>

The data which i am passing is below:

{"type":"bar","data":{"labels":["Feb 2020","Mar 2020","Apr 2020"],"datasets":[{"label":"DesignTracker","data":[1002.48,1076.93,439.53]},{"label":"cam","data":[2747.02,2532.73,472.41]},]},"options":{"legend":{"position":"top"},"scales":{"yAxes":[{"ticks":{"callback":function(value){return'$'+value;}}}]}}}

But the tooltip is not working. 

Can you please let me know what is the issue?

**Comment by typpo** [comment]
Could you please explain what you mean by tooltip?  Do you mean the information box that appears when you mouseover an image?  If so that is expected - Quickchart produces static images only, and not interactive Javascript.

**Comment by imanagemyschool** [comment]
Thank you for the response.

What i meant to say is when you mouseover a bar or pie you should be able to see the label which it shows. I see that functionality in the examples (like below)

![image](https://user-images.githubusercontent.com/23248731/79172477-a63a3900-7da9-11ea-9b2e-77c14e848611.png)

**Comment by typpo** [comment]
Quickchart is a static image generator, whereas the mouseovers are created in Javascript by Chart.js.  You can't have Javascript interactivity with a simple image.  For this reason it is impossible to have a static image that responds to mouseover.

**Comment by imanagemyschool** [comment]
Thank you very much for the explanation. That make sense.
