### ISSUE TITLE
font color

### ISSUE THREAD

**Issue by tyler71** [typpo/quickchart#52]
I'm not sure if this will be fixed in #49 as it seems to focus on background color,
I have this chart:
![](https://user-images.githubusercontent.com/4926565/80272529-6152b400-867f-11ea-86c6-20ab83788441.png)
```
/chart?encoding=base64&c=eyJkYXRhIjp7ImRhdGFzZXRzIjpbeyJkYXRhIjpbMjIwMDAsMjM1N10sImxhYmVsIjoiaW5wdXQifV0sImxhYmVscyI6WyJ1bml0ZWQtc3RhdGVzIiwiZ2VybWFueSJdfSwidHlwZSI6InBpZSJ9
```

I'd like to change the font color of the whole chart to a more readable one if possible.
I can't seem to find out how to do this in the documentation

**Comment by typpo** [comment]
QuickChart supports the chartjs-datalabels plugin for pie chart labels.  You can [follow these instructions](https://chartjs-plugin-datalabels.netlify.app/guide/labels.html) to modify labels.

Here's an example using the data you provided:

```
{
   "data":{
      "datasets":[
         {
            "data":[
               22000,
               2357
            ],
            "label":"input"
         }
      ],
      "labels":[
         "united-states",
         "germany"
      ]
   },
   "type":"pie",
   "options":{
      "plugins":{
         "datalabels":{
            "color":"#fff",
            "font":{
               "size":13,
               "weight":"bold"
            }
         }
      }
   }
}
```

![image](https://user-images.githubusercontent.com/310310/80287196-f9cf4f80-86e4-11ea-9043-7a1d947e19e2.png)

**Comment by tyler71** [comment]
Additionally, just for reference, this can set the legend font colors as well
https://www.chartjs.org/docs/latest/general/fonts.html?h=legend
```
    options: {
        legend: {
            labels: {
                // This more specific font property overrides the global property
                fontColor: 'black'
            }
        }
    }
```

Thank you for your help
