### ISSUE TITLE
horizontalBar type is greyed out

### ISSUE THREAD

**Issue by temp142** [typpo/quickchart#53]
Hi,
I am trying to create a horizontalBar chart, but I always get a grayscale image. It does not matter if the request is made by GET or POST method. 

Am I missing something or this chart type is not fully supported?
[
Generated chart](https://quickchart.io/chart?bkg=white&c=%7B%0A%20%20%20%20%22type%22%3A%20%22horizontalBar%22%2C%0A%20%20%20%20%22data%22%3A%20%7B%0A%20%20%20%20%20%20%22labels%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%221%2B%20yr%22%2C%0A%20%20%20%20%20%20%20%20%221%20-%2012%20months%22%2C%0A%20%20%20%20%20%20%20%20%221%20-%204%20weeks%22%2C%0A%20%20%20%20%20%20%20%20%22%3C%201%20week%22%0A%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%22datasets%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22label%22%3A%20%22Participants%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22data%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%2012%2C%0A%20%20%20%20%20%20%20%20%20%20%20%202%2C%0A%20%20%20%20%20%20%20%20%20%20%20%208%2C%0A%20%20%20%20%20%20%20%20%20%20%20%2024%0A%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%0A%20%20%7D)
Chart code (copied from another issue):

`
{
    "type": "horizontalBar",
    "data": {
       "labels": ["1+ yr","1 - 12 months","1 - 4 weeks","< 1 week"],
       "datasets": [
          {
              "label": "Participants",
              "data": [12,2,8,24]
           }
      ]
    }
}
`

**Comment by typpo** [comment]
This is just Chart.js's default behavior.  You can read more about setting backgroundColor for bar charts here:  https://www.chartjs.org/docs/latest/charts/bar.html#styling

For vertical bars, we add some default settings such as backgroundColor.  But you can always set it yourself!

Here's an example:
```
{ "type": "horizontalBar", "data": { "labels": ["1+ yr","1 - 12 months","1 - 4 weeks","< 1 week"], "datasets": [ { "label": "Participants", "data": [12,2,8,24], "backgroundColor": "red" } ] } }
```

![image](https://user-images.githubusercontent.com/310310/81362123-f351b800-9094-11ea-9aad-6b71c85fc486.png)
[link](https://quickchart.io/chart?bkg=white&c=%7B%20%22type%22%3A%20%22horizontalBar%22%2C%20%22data%22%3A%20%7B%20%22labels%22%3A%20%5B%221%2B%20yr%22%2C%221%20-%2012%20months%22%2C%221%20-%204%20weeks%22%2C%22%3C%201%20week%22%5D%2C%20%22datasets%22%3A%20%5B%20%7B%20%22label%22%3A%20%22Participants%22%2C%20%22data%22%3A%20%5B12%2C2%2C8%2C24%5D%2C%20%22backgroundColor%22%3A%20%22red%22%20%7D%20%5D%20%7D%20%7D)
