### ISSUE TITLE
how can I get GeoChart in quickchart

### ISSUE THREAD

**Issue by mquadrant** [typpo/quickchart#55]

**Comment by typpo** [comment]
Sorry, Quickchart doesn't support maps right now.  You may want to consider [Mapbox's static image API](https://docs.mapbox.com/api/maps/#static-images) or [Google's Static Maps API](https://developers.google.com/maps/documentation/maps-static/intro) (unlike Google Image Charts, this is not deprecated)

**Comment by mquadrant** [comment]
> Sorry, Quickchart doesn't support maps right now. You may want to consider [Mapbox's static image API](https://docs.mapbox.com/api/maps/#static-images) or [Google's Static Maps API](https://developers.google.com/maps/documentation/maps-static/intro) (unlike Google Image Charts, this is not deprecated)

thanks
