### ISSUE TITLE
Support organisational charts

### ISSUE THREAD

**Issue by Happypig375** [typpo/quickchart#57]
After reading through [the Google Image Charts shutdown announcement](https://groups.google.com/forum/?pli=1#!topic/google-chart-api/rZtHTyYgyXI%5B1-25%5D), I discovered this great project.

Since quickcharts.io is a drop-in replacement for chart.googleapis.com, it would make sense to implement all chart types available there.
Here is an example of organizational charts I am interested in:
```
https://chart.googleapis.com/chart?cht=gv&chl=digraph{C_0[shape=box];C_0->H_0[type=s];C_0->H_1[type=s];C_0->H_2[type=s];C_0->C_1[type=s];C_1->H_3[type=s];C_1->H_4[type=s];C_1->H_5[color=blue]}
```
![](https://chart.googleapis.com/chart?cht=gv&chl=digraph{C_0[shape=box];C_0->H_0[type=s];C_0->H_1[type=s];C_0->H_2[type=s];C_0->C_1[type=s];C_1->H_3[type=s];C_1->H_4[type=s];C_1->H_5[color=blue]})

The language used in this type of chart is called [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)).

I hoped that quickcharts.io can support such a chart, but unfortunately the charting library used (chart.js) is extremely change-averse:
- https://github.com/chartjs/Chart.js/issues/671
- https://github.com/chartjs/Chart.js/issues/5198

Therefore, an external plugin will have to be used.

I am forced to use image-charts.com for now, but I will definitely use an open-source alternative instead if available.
```
https://image-charts.com/chart?cht=gv&chl=digraph{C_0[shape=box];C_0->H_0[type=s];C_0->H_1[type=s];C_0->H_2[type=s];C_0->C_1[type=s];C_1->H_3[type=s];C_1->H_4[type=s];C_1->H_5[color=blue]}
```
![](https://image-charts.com/chart?cht=gv&chl=digraph{C_0[shape=box];C_0->H_0[type=s];C_0->H_1[type=s];C_0->H_2[type=s];C_0->C_1[type=s];C_1->H_3[type=s];C_1->H_4[type=s];C_1->H_5[color=blue]})

**Comment by typpo** [comment]
Hi @Happypig375, thanks for the request.

In #58 I've added support for graphviz rendering.  This has been merged and experimentally deployed to the public servers.

For example:

```
https://quickchart.io/chart?cht=gv&chl=digraph{C_0[shape=box];C_0-%3EH_0[type=s];C_0-%3EH_1[type=s];C_0-%3EH_2[type=s];C_0-%3EC_1[type=s];C_1-%3EH_3[type=s];C_1-%3EH_4[type=s];C_1-%3EH_5[color=blue]}
```

![QuickChart graphviz example](https://user-images.githubusercontent.com/310310/82847342-6be0b300-9ea2-11ea-953d-2eccb3dbdb71.png)

The render engine is the same for all three services, so you shouldn't notice a difference.

Some things to note
  - Supports only svg format for now
  - Output is auto-sized
  - You can specify layout engine by changing the `cht` parameter.  e.g. `cht:neato`.  Supported layout engines are circo, fdp, neato, osage, twopi, and dot (default)

Hope this helps and please let me know how it works for you!

**Comment by Happypig375** [comment]
The speed! Thanks a lot! :heart:

**Comment by Happypig375** [comment]
I am using quickchart.io for [a ReadMe on GitHub](https://github.com/verybadcat/CSharpMath#major-processes-of-drawing-latex). The rendered graphs are perfect when viewed on Windows but not on Android.

Windows:
![Windows](https://user-images.githubusercontent.com/19922066/82865381-2e8b2c80-9f59-11ea-8c83-17a5e5512a93.png)

Android:
![Android](https://user-images.githubusercontent.com/19922066/82865473-62665200-9f59-11ea-9466-4e4b37f14254.png)

On Android, the labels overlap with the edges. Is this a problem caused by the image format? I suppose PNG output can remedy this problem by enabling the same look across platforms.

**Comment by typpo** [comment]
Hmm, thanks for catching this.  Let me see if I can add PNG support.

**Comment by typpo** [comment]
Hi @Happypig375,

I've added PNG support.  Have a look at the following:

```
https://quickchart.io/chart?cht=gv&chl=digraph{C_0[shape=box];C_0->H_0[type=s];C_0->H_1[type=s];C_0->H_2[type=s];C_0->C_1[type=s];C_1->H_3[type=s];C_1->H_4[type=s];C_1->H_5[color=blue]}&chof=png&chs=300x180
```

Note the addition of the `chof` (format) and `chs` (size) parameters.  To generate a PNG, set `chof=png` and optionally provide a size.  If size isn't provided, it will auto size.

![image](https://user-images.githubusercontent.com/310310/82942231-82434900-9f4c-11ea-8c39-d447c0cd890c.png)

Let me know how this works for you.

**Comment by Happypig375** [comment]
It looks worse with PNG... Guess I'll stick with SVG then.
SVG: 
![SVG](https://quickchart.io/chart?cht=gv&chl=digraph{edge[label="%20"];{rank=same;"string%20(LaTeX%20math)";"string%20(LaTeX%20text)"};"string%20(LaTeX%20math)"->"CSharpMath.Atom.MathList"[taillabel="CSharpMath.Atom.LaTeXParser.MathListFromLaTeX%20"];"CSharpMath.Atom.MathList"->"string%20(LaTeX%20math)"[label="CSharpMath.Atom.LaTeXParser.MathListToLaTeX"];"CSharpMath.Atom.MathList"->"CSharpMath.Evaluation.MathItem"[label="CSharpMath.Evaluation.Evaluate"];"CSharpMath.Evaluation.MathItem"->"CSharpMath.Atom.MathList"[taillabel="CSharpMath.Evaluation.Parse%20%20"];"CSharpMath.Atom.MathList"->"CSharpMath.Display.IDisplay%3CTFont,%20TGlyph>"[label="CSharpMath.Display.Typesetter.CreateLine"];"string%20(LaTeX%20text)"->"CSharpMath.Rendering.Text.TextAtom"[label="CSharpMath.Rendering.Text.TextLaTeXParser.TextAtomFromLaTeX"];"CSharpMath.Rendering.Text.TextAtom"->"string%20(LaTeX%20text)"[taillabel="CSharpMath.Rendering.Text.TextLaTeXParser.TextAtomToLaTeX%20"];"CSharpMath.Rendering.Text.TextAtom"->"CSharpMath.Display.IDisplay%3CTFont,%20TGlyph>"[label="CSharpMath.Rendering.Text.TextTypesetter.Layout"];"CSharpMath.Display.IDisplay%3CTFont,%20TGlyph>"->"(Rendered%20output)"[label="CSharpMath.Display.IDisplay%3CTFont,%20TGlyph>.Draw"];"(Platform%20canvas)"->"CSharpMath.Rendering.FrontEnd.ICanvas"[label="%20CSharpMath.Rendering.FrontEnd.Painter%3CTCanvas,%20TContent,%20TColor>.WrapCanvas"];"CSharpMath.Rendering.FrontEnd.ICanvas"->"CSharpMath.Rendering.BackEnd.GraphicsContext"[label="%20new%20CSharpMath.Rendering.BackEnd.GraphicsContext"];"CSharpMath.Rendering.BackEnd.GraphicsContext"->"(Rendered%20output)"})

PNG:
![PNG](https://quickchart.io/chart?chof=png&cht=gv&chl=digraph{edge[label="%20"];{rank=same;"string%20(LaTeX%20math)";"string%20(LaTeX%20text)"};"string%20(LaTeX%20math)"->"CSharpMath.Atom.MathList"[taillabel="CSharpMath.Atom.LaTeXParser.MathListFromLaTeX%20"];"CSharpMath.Atom.MathList"->"string%20(LaTeX%20math)"[label="CSharpMath.Atom.LaTeXParser.MathListToLaTeX"];"CSharpMath.Atom.MathList"->"CSharpMath.Evaluation.MathItem"[label="CSharpMath.Evaluation.Evaluate"];"CSharpMath.Evaluation.MathItem"->"CSharpMath.Atom.MathList"[taillabel="CSharpMath.Evaluation.Parse%20%20"];"CSharpMath.Atom.MathList"->"CSharpMath.Display.IDisplay%3CTFont,%20TGlyph>"[label="CSharpMath.Display.Typesetter.CreateLine"];"string%20(LaTeX%20text)"->"CSharpMath.Rendering.Text.TextAtom"[label="CSharpMath.Rendering.Text.TextLaTeXParser.TextAtomFromLaTeX"];"CSharpMath.Rendering.Text.TextAtom"->"string%20(LaTeX%20text)"[taillabel="CSharpMath.Rendering.Text.TextLaTeXParser.TextAtomToLaTeX%20"];"CSharpMath.Rendering.Text.TextAtom"->"CSharpMath.Display.IDisplay%3CTFont,%20TGlyph>"[label="CSharpMath.Rendering.Text.TextTypesetter.Layout"];"CSharpMath.Display.IDisplay%3CTFont,%20TGlyph>"->"(Rendered%20output)"[label="CSharpMath.Display.IDisplay%3CTFont,%20TGlyph>.Draw"];"(Platform%20canvas)"->"CSharpMath.Rendering.FrontEnd.ICanvas"[label="%20CSharpMath.Rendering.FrontEnd.Painter%3CTCanvas,%20TContent,%20TColor>.WrapCanvas"];"CSharpMath.Rendering.FrontEnd.ICanvas"->"CSharpMath.Rendering.BackEnd.GraphicsContext"[label="%20new%20CSharpMath.Rendering.BackEnd.GraphicsContext"];"CSharpMath.Rendering.BackEnd.GraphicsContext"->"(Rendered%20output)"})

**Comment by typpo** [comment]
Overlapping labels are ultimately a graphviz layout problem and we won't be able to prevent them in this project.  You can try other graphviz layout engines, such as `neato` with `overlap="false"` and other engines like `fdp` that allow you to adjust a repulsion parameter.

For the default `dot` layout engine, you can use `ranksep` and `nodesep` to force more space:

```
https://quickchart.io/chart?cht=gv&chl=digraph{ranksep=3;nodesep=2;concentrate="true";edge[label=" "];{rank=same;"string (LaTeX math)";"string (LaTeX text)"};"string (LaTeX math)"->"CSharpMath.Atom.MathList"[taillabel="CSharpMath.Atom.LaTeXParser.MathListFromLaTeX "];"CSharpMath.Atom.MathList"->"string (LaTeX math)"[label="CSharpMath.Atom.LaTeXParser.MathListToLaTeX"];"CSharpMath.Atom.MathList"->"CSharpMath.Evaluation.MathItem"[label="CSharpMath.Evaluation.Evaluate"];"CSharpMath.Evaluation.MathItem"->"CSharpMath.Atom.MathList"[taillabel="CSharpMath.Evaluation.Parse%20 "];"CSharpMath.Atom.MathList"->"CSharpMath.Display.IDisplay<TFont, TGlyph>"[label="CSharpMath.Display.Typesetter.CreateLine"];"string (LaTeX text)"->"CSharpMath.Rendering.Text.TextAtom"[label="CSharpMath.Rendering.Text.TextLaTeXParser.TextAtomFromLaTeX"];"CSharpMath.Rendering.Text.TextAtom"->"string (LaTeX text)"[taillabel="CSharpMath.Rendering.Text.TextLaTeXParser.TextAtomToLaTeX "];"CSharpMath.Rendering.Text.TextAtom"->"CSharpMath.Display.IDisplay<TFont, TGlyph>"[label="CSharpMath.Rendering.Text.TextTypesetter.Layout"];"CSharpMath.Display.IDisplay<TFont, TGlyph>"->"(Rendered output)"[label="CSharpMath.Display.IDisplay<TFont, TGlyph>.Draw"];"(Platform canvas)"->"CSharpMath.Rendering.FrontEnd.ICanvas"[label=" CSharpMath.Rendering.FrontEnd.Painter<TCanvas, TContent, TColor>.WrapCanvas"];"CSharpMath.Rendering.FrontEnd.ICanvas"->"CSharpMath.Rendering.BackEnd.GraphicsContext"[label=" new CSharpMath.Rendering.BackEnd.GraphicsContext"];"CSharpMath.Rendering.BackEnd.GraphicsContext"->"(Rendered output)"}
```

Which looks a little bit better.  PNG:

![image](https://user-images.githubusercontent.com/310310/82980056-6025e700-9f9d-11ea-82f9-085703603605.png)

**Comment by Happypig375** [comment]
In the image provided, the labels are still overlapping with the edges though.

**Comment by Happypig375** [comment]
Still looks bad with `neato` and `overlap=false`.
```
https://quickchart.io/chart?cht=gv:neato&chl=digraph{overlap=false;edge[label=%22%20%22];{rank=same;%22string%20(LaTeX%20math)%22;%22string%20(LaTeX%20text)%22};%22string%20(LaTeX%20math)%22-%3E%22CSharpMath.Atom.MathList%22[taillabel=%22CSharpMath.Atom.LaTeXParser.MathListFromLaTeX%20%22];%22CSharpMath.Atom.MathList%22-%3E%22string%20(LaTeX%20math)%22[label=%22CSharpMath.Atom.LaTeXParser.MathListToLaTeX%22];%22CSharpMath.Atom.MathList%22-%3E%22CSharpMath.Evaluation.MathItem%22[label=%22CSharpMath.Evaluation.Evaluate%22];%22CSharpMath.Evaluation.MathItem%22-%3E%22CSharpMath.Atom.MathList%22[taillabel=%22CSharpMath.Evaluation.Parse%20%20%22];%22CSharpMath.Atom.MathList%22-%3E%22CSharpMath.Display.IDisplay%3CTFont,%20TGlyph%3E%22[label=%22CSharpMath.Display.Typesetter.CreateLine%22];%22string%20(LaTeX%20text)%22-%3E%22CSharpMath.Rendering.Text.TextAtom%22[label=%22CSharpMath.Rendering.Text.TextLaTeXParser.TextAtomFromLaTeX%22];%22CSharpMath.Rendering.Text.TextAtom%22-%3E%22string%20(LaTeX%20text)%22[taillabel=%22CSharpMath.Rendering.Text.TextLaTeXParser.TextAtomToLaTeX%20%22];%22CSharpMath.Rendering.Text.TextAtom%22-%3E%22CSharpMath.Display.IDisplay%3CTFont,%20TGlyph%3E%22[label=%22CSharpMath.Rendering.Text.TextTypesetter.Layout%22];%22CSharpMath.Display.IDisplay%3CTFont,%20TGlyph%3E%22-%3E%22(Rendered%20output)%22[label=%22CSharpMath.Display.IDisplay%3CTFont,%20TGlyph%3E.Draw%22];%22(Platform%20canvas)%22-%3E%22CSharpMath.Rendering.FrontEnd.ICanvas%22[label=%22%20CSharpMath.Rendering.FrontEnd.Painter%3CTCanvas,%20TContent,%20TColor%3E.WrapCanvas%22];%22CSharpMath.Rendering.FrontEnd.ICanvas%22-%3E%22CSharpMath.Rendering.BackEnd.GraphicsContext%22[label=%22%20new%20CSharpMath.Rendering.BackEnd.GraphicsContext%22];%22CSharpMath.Rendering.BackEnd.GraphicsContext%22-%3E%22(Rendered%20output)%22}
```
![image](https://user-images.githubusercontent.com/19922066/82980768-d3bb0900-a01c-11ea-925d-06eece531cef.png)

**Comment by typpo** [comment]
At least with the `dot` layout, `nodesep` and `ranksep` prevent the labels from overlapping each other.

Like I said, seems like a graphviz question.  All rendering engines - Google, Image Charts, QuickChart are using the same underlying graphviz library and layout engines (Google uses a slightly smaller font by default so it's a little better in your case).

There is lots of discussion about overlapping graphviz charts on StackOverflow.  These might help, but it will require you to spend some time wrangling graphviz:

https://stackoverflow.com/questions/24955769/how-to-prevent-edge-labels-from-messing-up-the-layout-in-graphviz
https://stackoverflow.com/questions/41969473/graphviz-overlapping-edge-labels
https://stackoverflow.com/questions/3967600/how-to-prevent-edges-in-graphviz-to-overlap-each-other
https://stackoverflow.com/questions/2476575/how-to-control-node-placement-in-graphviz-i-e-avoid-edge-crossings
