### ISSUE TITLE
small bar chart without axes, specific colors

### ISSUE THREAD

**Issue by randallt** [typpo/quickchart#6]
I am trying to migrate this chart, which is a 4-bucket distribution:

https://chart.apis.google.com/chart?cht=bvg&chs=150x22&chco=28BB64AA|ECA648|F38243|FF463C&chd=t:9491,484,203,6647&chf=bg,s,65432100&chds=-475.0,9970.0&chbh=a&chxt=x,y&chxs=0,,0,0,_|1,,0,0,_

![image](https://user-images.githubusercontent.com/7264834/55003625-bcab0200-4fa6-11e9-820a-3bcfa1dc1407.png)

to quickcharts.io.

Again, I am having trouble getting the settings right in the chart.js options. The parameters

chbh=a&chxt=x,y&chxs=0,,0,0,_|1,,0,0,_

at the end are just to make the axes disappear. This wasn't required with chart-images.com (but the watermark makes it unusable):

https://image-charts.com/chart?cht=bvg&chs=150x22&chco=28BB64AA|ECA648|F38243|FF463C&chd=t:9491,484,203,6647&chf=bg,s,65432100&chds=-475.0,9970.0

How can I do this with quickchart.io?

**Comment by typpo** [comment]
Based on the [documentation](https://www.chartjs.org/docs/latest/charts/bar.html), you are looking for something like this:

```
{
  type: 'bar',
  data: {
    datasets: [{
      backgroundColor: 'green',
      data: [50]
    }, {
      backgroundColor: 'yellow',
      data: [100]
    }, {
      backgroundColor: 'orange',
      data: [150]
    }, {
      backgroundColor: 'red',
      data: [200]
    }]
  },
  options: {
    scales: {
      xAxes: [{display: false}],
      yAxes: [{display: false}]
    },
    legend: {display: false}
  }
}
```

https://quickchart.io/chart?c=%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20backgroundColor%3A%20%27green%27%2C%0A%20%20%20%20%20%20data%3A%20%5B50%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20backgroundColor%3A%20%27yellow%27%2C%0A%20%20%20%20%20%20data%3A%20%5B100%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20backgroundColor%3A%20%27orange%27%2C%0A%20%20%20%20%20%20data%3A%20%5B150%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20backgroundColor%3A%20%27red%27%2C%0A%20%20%20%20%20%20data%3A%20%5B200%5D%0A%20%20%20%20%7D%5D%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20scales%3A%20%7B%0A%20%20%20%20%20%20xAxes%3A%20%5B%7Bdisplay%3A%20false%7D%5D%2C%0A%20%20%20%20%20%20yAxes%3A%20%5B%7Bdisplay%3A%20false%7D%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20legend%3A%20%7Bdisplay%3A%20false%7D%0A%20%20%7D%0A%7D

![image](https://user-images.githubusercontent.com/310310/55018617-7a86be00-4fb0-11e9-95f0-d5908cba1d47.png)

**Comment by randallt** [comment]
Does quickchart.io not support the 'indexable' attribute of some of these Chart.js options? We should be able to specify the colors in an array within the dataset, instead of separate datasets.

https://www.chartjs.org/docs/latest/general/options.html#indexable-options
https://www.chartjs.org/docs/latest/charts/bar.html#dataset-properties

When I tried this, it didn't work as expected:

{
  type: 'bar',
  data: {
    datasets: [{
      backgroundColor: ['green','yellow','orange','red'],
      data: [50,100,150,200]
    }]
  },
  options: {
    scales: {
      xAxes: [{display: false}],
      yAxes: [{display: false}]
    },
    legend: {display: false}
  }
}

https://quickchart.io/chart?c=%7Btype:'bar',data:%7Bdatasets:%5B%7BbackgroundColor:%5B'green','yellow','orange','red'%5D,data:%5B50,100,150,200%5D%7D%5D%7D,options:%7Bscales:%7BxAxes:%5B%7Bdisplay:false%7D%5D,yAxes:%5B%7Bdisplay:false%7D%5D%7D,legend:%7Bdisplay:false%7D%7D%7D

But maybe I got something wrong...

**Comment by randallt** [comment]
Got it to work. You HAVE to put in empty labels for some reason:

https://quickchart.io/chart?c=%7Btype:%27bar%27,data:%7Blabels:[%27%27,%27%27,%27%27,%27%27],datasets:%5B%7BbackgroundColor:%5B%27green%27,%27yellow%27,%27orange%27,%27red%27%5D,data:%5B50,100,150,200%5D%7D%5D%7D,options:%7Bscales:%7BxAxes:%5B%7Bdisplay:false%7D%5D,yAxes:%5B%7Bdisplay:false%7D%5D%7D,legend:%7Bdisplay:false%7D%7D%7D
