### ISSUE TITLE
URL shorting self-hosted?

### ISSUE THREAD

**Issue by boppy** [typpo/quickchart#61]
I can render charts with no problems on my self hosted Docker instance, but I cannot get the short link service to work.

As soon as I change the curl endpoint to the cloud hosted service (`https://quickchart.io/chart/create`) everything is running fine.

Is this a limitation to the OSS Version, the Docker Image, or am I missing something?

---

edit: Returned message is a HTML-Page with stating `Cannot POST /chart/create`.

**Comment by typpo** [comment]
Hi Henning,

The short link service is hosted separately from QuickChart and is therefore not part of this OSS project.  There are a variety of third-party and self-hosted link shorteners available.  You'd have to find one that suits your needs!
