### ISSUE TITLE
Sparkline collapses for some datasets if plot height is 30 or lower

### ISSUE THREAD

**Issue by malexan** [typpo/quickchart#62]
I am building a grid of sparklines and have found that for some datasets lines collapse to Y=0. 

Plot height 30, collapsing:

https://quickchart.io/chart?w=70&h=30&c={type:%27sparkline%27,options:{elements:{point:{radius:2}},scales:{yAxes:[{display:false,ticks:{suggestedMin:0}}]}},data:{datasets:[{data:[494,796,867,1049,880,5]}]}}

![image](https://user-images.githubusercontent.com/1481851/86125475-6439ad00-bae5-11ea-8c61-23d0e4e115b8.png)

Height 31, normal.

https://quickchart.io/chart?w=70&h=31&c={type:%27sparkline%27,options:{elements:{point:{radius:2}},scales:{yAxes:[{display:false,ticks:{suggestedMin:0}}]}},data:{datasets:[{data:[494,796,867,1049,880,5]}]}}

![image](https://user-images.githubusercontent.com/1481851/86125795-e7f39980-bae5-11ea-928d-948e07887b0a.png)

Other datasets don't care.

https://quickchart.io/chart?w=70&h=30&c={type:%27sparkline%27,options:{elements:{point:{radius:2}},scales:{yAxes:[{display:false,ticks:{suggestedMin:0}}]}},data:{datasets:[{data:[1080,1512,2596,3068,2860,17]}]}}

![image](https://user-images.githubusercontent.com/1481851/86126010-4751a980-bae6-11ea-904f-d8f16ca55a49.png)

**Comment by malexan** [comment]
30 pixels is not a pivot point. The proportion of the spark to the height of the plot is changing:

31 pixels:
![image](https://user-images.githubusercontent.com/1481851/86127201-31dd7f00-bae8-11ea-9778-42c0db9acf76.png)


40 pixels:
![image](https://user-images.githubusercontent.com/1481851/86127253-428df500-bae8-11ea-94ba-634708036703.png)

50 pixels:
![image](https://user-images.githubusercontent.com/1481851/86127310-5b96a600-bae8-11ea-8508-feac3dc09305.png)

100 pixels:
![image](https://user-images.githubusercontent.com/1481851/86127429-85e86380-bae8-11ea-9d11-fa64dd37761a.png)

300 pixels:
![image](https://user-images.githubusercontent.com/1481851/86127458-9698d980-bae8-11ea-90f0-a1e260dfe847.png)


https://quickchart.io/chart?w=70&h=500&c={type:%27sparkline%27,options:{elements:{point:{radius:2}},scales:{yAxes:[{display:false,ticks:{suggestedMin:0}}]}},data:{datasets:[{data:[1080,1512,2596,3068,2860,17]}]}}

**Comment by typpo** [comment]
Hi Alexander, I'm looking into it.  Charts with small dimensions have issues with axes collapsing, probably due to chart margins or something.  

In the meantime I suggest you use larger dimensions to generate the image and then set the image size in html/css.

**Comment by typpo** [comment]
This issue has been resolved :)
