### ISSUE TITLE
Getting error message when passing graph through api

### ISSUE THREAD

**Issue by eoinparkinson** [typpo/quickchart#63]
Hi,

I built myself a simple Python api to convert the Quickchart graph to base64. The api does as should, and the graph I pass through works fine in web browser, but when it's passed through the api it spits out this error every time:
![image](https://user-images.githubusercontent.com/48634511/87260398-9d8cf800-c4a9-11ea-9141-ea9825ab6d6b.png)

I am lost on where to go from here. This graph works fine in web browsers, but the api breaks it. When testing other image examples online, the api does not break them.

Is it an issue of the graph not being built in time and my api is spitting out the response too quick?

Thanks,
Eoin.

**Comment by typpo** [comment]
Hi Eoin, are you able to share your API code or at least show how the request is being built?  That way I can tell you what's wrong with the request.

**Comment by eoinparkinson** [comment]
Yes of course. Sorry I should have included this in the original post. 

[base64-img.zip](https://github.com/typpo/quickchart/files/4912100/base64-img.zip)

The API is active on `api.eoinparkinson.com/api/v1/img-base64?url=` - Set the url parameter to the quickchart url. I created my own API because another API I was using online was spitting errors, but it appears mines is also doing this.

Thanks, Eoin.

**Comment by typpo** [comment]
It's a URL encoding issue.  To pass in a URL as a query parameter, you need to URL-encode the whole thing:

http://api.eoinparkinson.com/api/v1/img-base64?url=https%3A%2F%2Fquickchart.io%2Fchart%3Fbkg%3Dwhite%26c%3D{type%3A'bar'%2Cdata%3A{labels%3A[2012%2C2013%2C2014%2C2015%2C2016]%2Cdatasets%3A[{label%3A'Users'%2Cdata%3A[120%2C60%2C50%2C180%2C120]}]}}

Note that in the QuickChart URL, the `chart` query parameter is URL-encoded itself.

**Comment by eoinparkinson** [comment]
Okay. URL encoding is now completely new to me. Would I be able to push this direct to the api and let the Python script convert this for me? Or must I convert this client side first. 

Thanks again for your help, much appreciated.

**Comment by typpo** [comment]
It's best to convert it on the client first!  URL encoding allows the server to parse your URL properly.  Otherwise, it's hard to say what you'll get in Flask, especially for more complicated URLs.

On a Javascript client, you can do this simply with `encodeURIComponent`:

```js
var url = 'http://api.eoinparkinson.com/api/v1/img-base64?url=' + encodeURIComponent(quickchartUrl)
```

Hope this helps!

**Comment by eoinparkinson** [comment]
I'll take a look at this tomorrow morning. Many thanks for this.

**Comment by eoinparkinson** [comment]
I'm using http request, how can I add this to the Header to encode it, or is this possible? Sorry for bugging you. It's a Thunkable application and so I don't have much access to the api or app js. Thanks.

**Comment by typpo** [comment]
Possibly related question, can you show me how you're constructing the QuickChart chart object?  Screenshot of Thunkable is ok.  I'm wondering if you need to encode that as well.

**Comment by eoinparkinson** [comment]
Yes of course.
![image](https://user-images.githubusercontent.com/48634511/87482337-1f575f80-c629-11ea-936b-90b9fa3c09d0.png)

The text input at the very end was just for testing the error'd graph. Breakdown of the variables.

- selectedGraphType is either "bar" or "line" and works as should.
- tmpRecordingLabels contains human time stamps that look like ["19:20","19:22","19:25"] which are just 24hr time labels. When you said url encoding I thought the ":" might mess it up.
- tmpVal is just a date string label that looks like "25-05-2020"
- selectedColour is the rgba colour.
- tmpSelectedRecordingData is a list of intigers [3,2,6,3,5] and so on.

An image of what it looks like:
![image](https://user-images.githubusercontent.com/48634511/87482655-c89e5580-c629-11ea-8169-6ba6fe0a7563.png)

If this is extra work for you don't stress it. I'm glad I know now it is an issue of url encoding. That's something I need to look into. The API component provides me with a **Header** properties.
![image](https://user-images.githubusercontent.com/48634511/87482746-f84d5d80-c629-11ea-9b72-3b42cbcb020a.png)
You can see here a solution I tried but again Header property's are something I've never used before. 

Thanks again, Eoin.

**Comment by typpo** [comment]
One more question just so I understand fully.  Why are you going hosting your own server to send the request to QuickChart instead of sending the request directly?  Is it because you need the image in base 64 text format instead of png?

**Comment by eoinparkinson** [comment]
Yes this is only so I can share the image to save it to camera roll on my device. 

I tried using the encode parameter for Quickchart and it didn't work. I found it on an outdated looking website. 

Thanks.

**Comment by typpo** [comment]
Hey Eoin, just saw your edit.  I was going to suggest that you POST, that will save you the trouble of encoding it.  You can POST directly to the `/chart` endpoint and receive an image in return, or POST to the `/chart/create` endpoint and receive a URL in return.

**Comment by eoinparkinson** [comment]
Hi Ian thanks for that. Shooting out an error here on my end with POST, it requests a JSON. I've seen something similar to this before, must I post this through the api `body`? Thanks. 
![image](https://user-images.githubusercontent.com/48634511/88537566-b519c400-d005-11ea-9cab-e0d01b5f1bbc.jpeg)

**Comment by eoinparkinson** [comment]
Spoke to Jared, he told me to use the `body` block to pass through the chart info, but I must not be formatting it correctly. Using the header `Content-Type: application/json`. Chart JSON taken from example on docs. Here's what I've got.
![image](https://user-images.githubusercontent.com/48634511/88727219-15545700-d127-11ea-9d85-f68129c51a79.png)
Response: 
`{
  "success": false,
  "error": "Expecting POST with Content-Type application/json"
}`

Response is the same without `generate JSON from object` block.

Again thanks for your help on this, Eoin.

**Comment by eoinparkinson** [comment]
Just wanted to say I got this working in the end. I had a very messy start at this but got everything cleaned up and correctly formatted json. I'm wondering am I able to sort label values into one label or must I do this locally first?

What I mean is: labels `["a","a","b"]` and values `[2,1,4]` and produce `a=3` and `b=4`. Is this possible for the graph to do this work for me like I would get in something like Plotly?

Thanks.

**Comment by typpo** [comment]
Hi @eoinparkinson, really glad to hear you got it working and sorry I wasn't more help! (and sorry I missed your final question).

Chart.js doesn't have a built-in way to do aggregation like you suggest.  Unfortunately, you'd have to figure out a way to send a=3 and b=4 on your end.
