### ISSUE TITLE
Font Error

### ISSUE THREAD

**Issue by kyawsuthway-onow** [typpo/quickchart#65]
I have been using quick for a long time.
But Just three days ago I had a font error in the Myanmar language.
It was fine before.

![image](https://user-images.githubusercontent.com/68676228/89506497-34bb4600-d7f1-11ea-951e-12c2ee2937f2.png)

Now it only shows like this.

![image](https://user-images.githubusercontent.com/68676228/89506594-5d434000-d7f1-11ea-9c17-85f5dded3a2b.png)

**Comment by typpo** [comment]
Hi @kyawsuthway-onow, I've corrected the issue.  Your previous queries are cached, so you will have to create new charts or add a cache-busting parameter to the URL (e.g. `t=abc123`).

![Burmese quickchart](https://user-images.githubusercontent.com/310310/89609392-f3e52080-d834-11ea-8ac6-5515e01ca866.png)

https://quickchart.io/chart?bkg=white&c=%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%27Q1%27%2C%20%27Q2%27%2C%20%27Q3%27%2C%20%27Q4%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20label%3A%20%27%E1%80%99%E1%80%BC%E1%80%94%E1%80%BA%E1%80%99%E1%80%AC%E1%80%A1%E1%80%80%E1%80%B9%E1%80%81%E1%80%9B%E1%80%AC%27%2C%0A%20%20%20%20%20%20data%3A%20%5B50%2C%2060%2C%2070%2C%20180%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20label%3A%20%27Revenue%27%2C%0A%20%20%20%20%20%20data%3A%20%5B100%2C%20200%2C%20300%2C%20400%5D%0A%20%20%20%20%7D%5D%0A%20%20%7D%0A%7D

**Comment by 5003** [comment]
Hi, @typpo
The same problem occurs when Half-width Katakana characters.

![](https://quickchart.io/chart?c=%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%27January%27%2C%20%27February%27%2C%20%27March%27%2C%20%27April%27%2C%20%27May%27%2C%20%27June%27%2C%20%27July%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%27%EF%BD%B1%EF%BD%B2%EF%BE%83%EF%BE%91%201%27%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%27rgba(255%2C%2099%2C%20132%2C%200.5)%27%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%27rgb(255%2C%2099%2C%20132)%27%2C%0A%20%20%20%20%20%20%20%20borderWidth%3A%201%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B-31%2C%20-70%2C%20-30%2C%20-33%2C%20-9%2C%2014%2C%20-41%5D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%27%EF%BD%B1%EF%BD%B2%EF%BE%83%EF%BE%91%202%27%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%27rgba(54%2C%20162%2C%20235%2C%200.5)%27%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%27rgb(54%2C%20162%2C%20235)%27%2C%0A%20%20%20%20%20%20%20%20borderWidth%3A%201%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B73%2C%2041%2C%2029%2C%2061%2C%20-65%2C%2059%2C%2038%5D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20title%3A%20%7B%0A%20%20%20%20%20%20display%3A%20true%2C%0A%20%20%20%20%20%20text%3A%20%27%EF%BE%98%EF%BD%BD%EF%BE%84%27%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20plugins%3A%20%7B%0A%20%20%20%20%20%20datalabels%3A%20%7B%0A%20%20%20%20%20%20%20%20anchor%3A%20%27center%27%2C%0A%20%20%20%20%20%20%20%20align%3A%20%27center%27%2C%0A%20%20%20%20%20%20%20%20color%3A%20%27%23666%27%2C%0A%20%20%20%20%20%20%20%20font%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20weight%3A%20%27normal%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D%2C%0A%7D%0A)
https://quickchart.io/chart?c=%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%27January%27%2C%20%27February%27%2C%20%27March%27%2C%20%27April%27%2C%20%27May%27%2C%20%27June%27%2C%20%27July%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%27%EF%BD%B1%EF%BD%B2%EF%BE%83%EF%BE%91%201%27%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%27rgba(255%2C%2099%2C%20132%2C%200.5)%27%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%27rgb(255%2C%2099%2C%20132)%27%2C%0A%20%20%20%20%20%20%20%20borderWidth%3A%201%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B-31%2C%20-70%2C%20-30%2C%20-33%2C%20-9%2C%2014%2C%20-41%5D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%27%EF%BD%B1%EF%BD%B2%EF%BE%83%EF%BE%91%202%27%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%27rgba(54%2C%20162%2C%20235%2C%200.5)%27%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%27rgb(54%2C%20162%2C%20235)%27%2C%0A%20%20%20%20%20%20%20%20borderWidth%3A%201%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B73%2C%2041%2C%2029%2C%2061%2C%20-65%2C%2059%2C%2038%5D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20title%3A%20%7B%0A%20%20%20%20%20%20display%3A%20true%2C%0A%20%20%20%20%20%20text%3A%20%27%EF%BE%98%EF%BD%BD%EF%BE%84%27%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20plugins%3A%20%7B%0A%20%20%20%20%20%20datalabels%3A%20%7B%0A%20%20%20%20%20%20%20%20anchor%3A%20%27center%27%2C%0A%20%20%20%20%20%20%20%20align%3A%20%27center%27%2C%0A%20%20%20%20%20%20%20%20color%3A%20%27%23666%27%2C%0A%20%20%20%20%20%20%20%20font%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20weight%3A%20%27normal%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D%2C%0A%7D%0A

**Comment by typpo** [comment]
Hi @5003, thanks for the report.  This has been fixed

![katakana quickchart](https://user-images.githubusercontent.com/310310/211385075-b1ee9e7c-4c38-4909-9428-28e84a5a9d4a.png)

**Comment by 5003** [comment]
Hi, @typpo

Thanks!
Same error occurs again, using a Graphviz.

![](https://quickchart.io/graphviz?format=png&graph=digraph{node[shape=record];a[label=%22%EF%BD%B8%EF%BE%9E%EF%BE%99%EF%BD%B0%EF%BE%8C%EF%BE%9F|{%E7%AC%AC1|%E7%AC%AC2}|{%E5%90%8D%E5%89%8D|%E5%90%8D%E5%89%8D}%22];})
