### ISSUE TITLE
Reccomended memory allocation for docker container?

### ISSUE THREAD

**Issue by jojenreed** [typpo/quickchart#66]
What is the reccomended allocation memory and compute wise if I were to go the self-hosting route? We might not be able to use the quickchart.io service directly due to compliance requirements.

**Comment by typpo** [comment]
Hi @jojenreed, it depends a bit on the size & type of charts you are rendering, but generally 1024mb is enough RAM and you can probably get by with 512.  Compute-wise I don't think there are any hard requirements.  This does not take into account the possibility of concurrent requests.
