### ISSUE TITLE
Doughnut Labels Disappear at Random Font Sizes 

### ISSUE THREAD

**Issue by danieljoeblack** [typpo/quickchart#70]
I'm using a doughnut type graph with the chartjs-plugin-doughnutlabel  plugin and have noticed an intermittent issue with label disappearing entirely from the graph. [Here ](https://quickchart.io/sandbox/#%7B%0A%20%20%20%22data%22%3A%7B%0A%20%20%20%20%20%20%22datasets%22%3A%5B%0A%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22data%22%3A%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2066.0%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2037.0%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2024.0%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%208.0%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22backgroundColor%22%3A%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%235DA5DA%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%23FAA43A%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%2360BD68%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%23F17CB0%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%23F15854%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%23DECF3F%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%23B276B2%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%23B2912F%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%234D4D4D%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%22labels%22%3A%5B%0A%20%20%20%20%20%20%20%20%20%22UPS%20GROUND%22%2C%0A%20%20%20%20%20%20%20%20%20%22CANADA%20POST%22%2C%0A%20%20%20%20%20%20%20%20%20%22PUROLATOR%20GROUND%22%2C%0A%20%20%20%20%20%20%20%20%20%22DICOM%20GROUND%22%0A%20%20%20%20%20%20%5D%0A%20%20%20%7D%2C%0A%20%20%20%22options%22%3A%7B%0A%20%20%20%20%20%20%22plugins%22%3A%7B%0A%20%20%20%20%20%20%20%20%20%22legend%22%3Afalse%2C%0A%20%20%20%20%20%20%20%20%20%22outlabels%22%3A%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22text%22%3A%22%25l%5Cn%25v%20(%25p)%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22color%22%3A%22white%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22stretch%22%3A35%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22font%22%3A%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22resizable%22%3Atrue%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22minSize%22%3A12%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22maxSize%22%3A18%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%22doughnutlabel%22%3A%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22labels%22%3A%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22text%22%3A%22135.5%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22font%22%3A%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22size%22%3A23%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22color%22%3A%22black%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%7D%2C%0A%20%20%20%22type%22%3A%22outlabeledDoughnut%22%0A%7D)is an example of the issue using the sandbox.

The label appears when first hitting the link, but if the `doughnutlabels` > `labels` > `font` > `size` value is update to say `24` the label disappears. incrementing the value up the label doesn't reappear until a size of `27` is reached. 

![image](https://user-images.githubusercontent.com/25334048/96026706-e3e55080-0e24-11eb-9a33-e4e0fb5b31a8.png)

![image](https://user-images.githubusercontent.com/25334048/96026737-ee9fe580-0e24-11eb-81c0-6c63681e6035.png)

It also seems that changing the value for  `doughnutlabels` > `labels` > `text` from a string type to a numerical type also has an effect. Setting the size to 17 does not show the label UNTIL the text is changed to a numerical type (removed the quotes).

![image](https://user-images.githubusercontent.com/25334048/96027180-81d91b00-0e25-11eb-8081-7588e5f025ce.png)

![image](https://user-images.githubusercontent.com/25334048/96027217-8dc4dd00-0e25-11eb-802d-039c84140000.png)

I can't seem to find a reason for this behaviour.

**Comment by typpo** [comment]
Thanks for the report, it's interesting and not sure what's going on yet.  Perhaps some interaction between outlabels and doughtnutlabels plugins.

[jsfiddle](https://jsfiddle.net/typpo/9b6t5wfz/1/) looks ok.  Setting the width and the height explicitly in the image (e.g. `?width=500&height=500`) also appears to solve the issue.

**Comment by danieljoeblack** [comment]
Thanks for looking into it. I've done some initial testing with adding the width and height, it has prevented the issue in every case I've tried so far. We shouldn't have a problem using this work around and it's not something I would have thought to try so thanks for pointing it out!

P.S. Thank you for making this tool available, it is awesome :)

**Comment by danieljoeblack** [comment]
Some more information, I was doing some more testing with this workaround and it doesn't seem to always work. Take [this url](https://quickchart.io/chart?width=600&height=400&bkg=white&c=%7B%22data%22%3A%7B%22datasets%22%3A%5B%7B%22data%22%3A%5B222.0%2C124.0%2C85.0%2C20.0%5D%2C%22backgroundColor%22%3A%5B%22%235DA5DA%22%2C%22%23FAA43A%22%2C%22%2360BD68%22%2C%22%23F17CB0%22%2C%22%23F15854%22%2C%22%23DECF3F%22%2C%22%23B276B2%22%2C%22%23B2912F%22%2C%22%234D4D4D%22%5D%7D%5D%2C%22labels%22%3A%5B%22UPS+GROUND%22%2C%22CANADA+POST%22%2C%22PUROLATOR+GROUND%22%2C%22DICOM+GROUND%22%5D%7D%2C%22type%22%3A%22outlabeledDoughnut%22%2C%22options%22%3A%7B%22plugins%22%3A%7B%22legend%22%3Afalse%2C%22outlabels%22%3A%7B%22text%22%3A%22%25l%5Cn%25v+%28%25p%29%22%2C%22color%22%3A%22white%22%2C%22stretch%22%3A35%2C%22font%22%3A%7B%22resizable%22%3Atrue%2C%22minSize%22%3A12%2C%22maxSize%22%3A18%7D%7D%2C%22doughnutlabel%22%3A%7B%22labels%22%3A%5B%7B%22text%22%3A%22451%22%2C%22font%22%3A%7B%22size%22%3A30%7D%2C%22color%22%3A%22black%22%7D%5D%7D%7D%7D%7D) which includes width and height in the url, but is not displaying the doughnut label. Changing the width can cause it to come back (in this case changing width to `650` ) but there doesn't seem to be a single width that will always work.

**Comment by typpo** [comment]
I haven't forgotten about this - still looking into it.

**Comment by typpo** [comment]
This turned out to be a problem with QuickChart itself.  The `doughnutlabel` plugin was only being loaded for charts with type `doughnut` and not `outlabeledDoughnut`.  This means that the center text failed to appear for outlabeled charts on chart servers that had used a `doughnutlabel` with a normal doughnut chart before, which is why the bug was not occurring deterministically...

Note that the public endpoint is cached, so you'll have to change something about your chart definition in order to see center labels consistently.

Thanks for your patience and thanks for reporting this issue!
