### ISSUE TITLE
How to embed Emoji as labels ?

### ISSUE THREAD

**Issue by iagustian** [typpo/quickchart#71]
I was trying to embed Emojis, but the result is a decoded text like this.

<img width="1209" alt="Screen Shot 2020-10-19 at 13 02 16" src="https://user-images.githubusercontent.com/6878198/96407385-7877f600-120b-11eb-972b-0aae030ca550.png">

Any steps I missed?

**Comment by typpo** [comment]
Hi Ian, the public renderer comes with an emoji set installed: Open Sans Emoji.  All emojis are in _monochrome_, meaning you won't get the colorful emoji you may be used to.  If you self-host, you can install whatever emoji you like on the machine.

The eyes emoji should work... can you tell me more about the request you are using to generate the graph?

![chart.js with emoji](https://user-images.githubusercontent.com/310310/96475423-dd6e2480-11e8-11eb-8218-7ffdea305122.png)

```
{
  type: 'bar',
  data: {
    labels: ['Q1', 'Q2', 'Q3', 'Q4'],
    datasets: [{
      label: '👀 Users',
      data: [50, 60, 70, 180]
    }, {
      label: 'Revenue',
      data: [100, 200, 300, 400]
    }]
  }
}
```

[link](https://quickchart.io/chart?bkg=white&c=%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%27Q1%27%2C%20%27Q2%27%2C%20%27Q3%27%2C%20%27Q4%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20label%3A%20%27%F0%9F%91%80%20Users%27%2C%0A%20%20%20%20%20%20data%3A%20%5B50%2C%2060%2C%2070%2C%20180%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20label%3A%20%27Revenue%27%2C%0A%20%20%20%20%20%20data%3A%20%5B100%2C%20200%2C%20300%2C%20400%5D%0A%20%20%20%20%7D%5D%0A%20%20%7D%0A%7D)

**Comment by iagustian** [comment]
Hi @typpo thanks for such detailed reply, I use the self-hosted version of quickchart io.
So what should I do to support such emoji on my generated chart. Or did i miss certain steps when installing the open source version?
P.S. I installed the quickchart using docker version

**Comment by typpo** [comment]
Hey @iagustian, the Docker image has been updated to include emoji fonts.  It has been tagged as v1.4.2 along with some other fixes and improvements.  Thanks for reporting this issue!

**Comment by typpo** [comment]
You could perhaps install the Noto Color Emoji font: https://fonts.google.com/noto/specimen/Noto+Color+Emoji

**Comment by viktornord** [comment]
Nay, it becomes 
![image](https://github.com/typpo/quickchart/assets/2639135/296e1862-64b1-4776-abe3-bb52348e4852)

**Comment by viktornord** [comment]
Please add this feature support @typpo

**Comment by viktornord** [comment]
@typpo do you mean to spin up own server with this docker image and add fonts instead of using `https://quickchart.io/`
