### ISSUE TITLE
PHP and callback problem

### ISSUE THREAD

**Issue by Meywether** [typpo/quickchart#72]
Hello everyone,
thanks for your great job and service you are providing to the community.
I am currently struggling with PHP and the callback within the JSON object.
My chart code in PHP looks like:

```         $data = array(
            'chart' => array(
                'type' => 'horizontalBar',
                'data' => array(
                    'labels' => ['comm', 'team', 'dialog'],
                    'datasets' => [
                        array(
                            'data' => [40, 60, 80],
                            'categoryPercentage' => 1,
                            'backgroundColor' => [
                                'rgba(12, 194, 178, 1)',
                                'rgba(12, 194, 178, 1)',
                                'rgba(12, 194, 178, 1)'
                            ]
                        )
                    ]
                ),
                'options' => array(
                    'layout' => array(
                        'padding' => array(
                            'left' => 100
                        )
                    ),
                    'legend' => array(
                        'display' => false
                    ),
                    'scales' => array(
                        'xAxes' => [
                            array(
                            'ticks' => array(
                                'min' => 0,
                                'max' => 100,
                                'fontsize' => 16,
                                'fontColor' => 'black',
                                'fontFamily' => 'Arial',
                                'callback' => "function(value) { return value + '%'; }" // -> here you can see the problem 
                            )
                        )
                        ],
                        'yAxes' => [
                            array(
                                'ticks' => array(
                                    'fontsize' => 16,
                                    'fontColor' => 'black',
                                    'fontFamily' => 'Arial'
                                )
                            )
                        ]
                    )
                )
            )
```

Everytime the api complains about callback is not a function.

I already looked at many posts and I know that the whole object should be a string, after json_encode the object looks:
``` 
{
	"chart": {
		"type": "horizontalBar",
		"data": {
			"labels": [
				"comm",
				"team",
				"dialog"
			],
			"datasets": [
				{
					"data": [
						40,
						60,
						80
					],
					"categoryPercentage": 1,
					"backgroundColor": [
						"rgba(12, 194, 178, 1)",
						"rgba(12, 194, 178, 1)",
						"rgba(12, 194, 178, 1)"
					]
				}
			]
		},
		"options": {
			"layout": {
				"padding": {
					"left": 100
				}
			},
			"legend": {
				"display": false
			},
			"scales": {
				"xAxes": [
					{
						"ticks": {
							"min": 0,
							"max": 100,
							"fontsize": 16,
							"fontColor": "black",
							"fontFamily": "Arial",
							"callback": "function(value) { return value + '%'; }"  // -> you see the problem? The function is still a string and this ends up in an error. 
						}
					}
				],
				"yAxes": [
					{
						"ticks": {
							"fontsize": 16,
							"fontColor": "black",
							"fontFamily": "Arial"
						}
					}
				]
			}
		}
	}
}
```

So as you can see, the json is a valid object but the function is still a string.

Also changing the line with other ticks ```'callback' => 'function(value) { return value + "%"; }'``` return after json_encode in: ```"callback":"function(value) { return value + \"%\"; }"```

So i am a little bit stuck in this, I just want to have my xAxes with '%'. (10%, 20%....)

Changing callback to formatter works, but without '%'

I also tried the approach by replacing a placeholder with the function code, but this resulted in a 500 error. 

So to summon up: The chart is rendered without the callback, but with it, won't work!

![image](https://user-images.githubusercontent.com/39849054/97730972-d7bfeb00-1ad4-11eb-861a-fa2cdde35bee.png)

May I ask for your help?

Thanks in advance!
Meywether

**Comment by typpo** [comment]
Hi @Meywether, the easiest way to accomplish what you want is to set `chart` as a Chart.js Javascript string, with `callback` as a Javascript function.

For example:

```php
$config = "{
  type: 'horizontalBar',
  data: {
    labels: ['comm', 'team', 'dialog'],
    datasets: [
      {
        data: [40, 60, 80],
        categoryPercentage: 1,
        backgroundColor: [
          'rgba(12, 194, 178, 1)',
          'rgba(12, 194, 178, 1)',
          'rgba(12, 194, 178, 1)',
        ],
      },
    ],
  },
  options: {
    layout: {
      padding: {
        left: 100,
      },
    },
    legend: {
      display: false,
    },
    scales: {
      xAxes: [
        {
          ticks: {
            min: 0,
            max: 100,
            fontsize: 16,
            fontColor: 'black',
            fontFamily: 'Arial',
            callback: function (value) {
              return value + '%';
            },
          },
        },
      ],
      yAxes: [
        {
          ticks: {
            fontsize: 16,
            fontColor: 'black',
            fontFamily: 'Arial',
          },
        },
      ],
    },
  },
}";

$chartUrl = 'https://quickchart.io/chart?w=500&h=300&bkg=white&c=' . urlencode($config);
echo $chartUrl;
```

[generated url](https://quickchart.io/chart?w=500&h=300&bkg=white&c=%7B%0A++type%3A+%27horizontalBar%27%2C%0A++data%3A+%7B%0A++++labels%3A+%5B%27comm%27%2C+%27team%27%2C+%27dialog%27%5D%2C%0A++++datasets%3A+%5B%0A++++++%7B%0A++++++++data%3A+%5B40%2C+60%2C+80%5D%2C%0A++++++++categoryPercentage%3A+1%2C%0A++++++++backgroundColor%3A+%5B%0A++++++++++%27rgba%2812%2C+194%2C+178%2C+1%29%27%2C%0A++++++++++%27rgba%2812%2C+194%2C+178%2C+1%29%27%2C%0A++++++++++%27rgba%2812%2C+194%2C+178%2C+1%29%27%2C%0A++++++++%5D%2C%0A++++++%7D%2C%0A++++%5D%2C%0A++%7D%2C%0A++options%3A+%7B%0A++++layout%3A+%7B%0A++++++padding%3A+%7B%0A++++++++left%3A+100%2C%0A++++++%7D%2C%0A++++%7D%2C%0A++++legend%3A+%7B%0A++++++display%3A+false%2C%0A++++%7D%2C%0A++++scales%3A+%7B%0A++++++xAxes%3A+%5B%0A++++++++%7B%0A++++++++++ticks%3A+%7B%0A++++++++++++min%3A+0%2C%0A++++++++++++max%3A+100%2C%0A++++++++++++fontsize%3A+16%2C%0A++++++++++++fontColor%3A+%27black%27%2C%0A++++++++++++fontFamily%3A+%27Arial%27%2C%0A++++++++++++callback%3A+function+%28value%29+%7B%0A++++++++++++++return+value+%2B+%27%25%27%3B%0A++++++++++++%7D%2C%0A++++++++++%7D%2C%0A++++++++%7D%2C%0A++++++%5D%2C%0A++++++yAxes%3A+%5B%0A++++++++%7B%0A++++++++++ticks%3A+%7B%0A++++++++++++fontsize%3A+16%2C%0A++++++++++++fontColor%3A+%27black%27%2C%0A++++++++++++fontFamily%3A+%27Arial%27%2C%0A++++++++++%7D%2C%0A++++++++%7D%2C%0A++++++%5D%2C%0A++++%7D%2C%0A++%7D%2C%0A%7D)

![php chart example](https://user-images.githubusercontent.com/310310/97790789-d9e38180-1b88-11eb-9bf8-ddee6264ca84.png)

**Comment by typpo** [comment]
👍  Glad you fixed it and thank you for sharing your solution!

The limit is 60 charts/min/ip.  If you are using it for business I still recommend using a paid plan as the rate limit could change and free-tier API performance can vary based on load.
