### ISSUE TITLE
CanvasGradient not defined when rendering line charts

### ISSUE THREAD

**Issue by TuxGamer** [typpo/quickchart#73]
In the self-hosted versions, both running the DockerHub's image and the self-built one, line chart appear to not be working at all.
I have not been able to get the library to compile on Debian 10 with Node v14.15 since node-pre-gyp complains about missing properties in package.json

It just says: "Chart Error: Canvas Gradient is not defined".

The message is also displayed in the container's log, but no stack trace is being printed.

Here are some URLs that work fine on the hosted variant, but not locally:
Demo Graph from repository's readme:
https://quickchart.io/chart?width=500&height=300&c=%7Btype:%27bar%27,data:%7Blabels:%5B%27January%27,%27February%27,%27March%27,%27April%27,%27May%27%5D,datasets:%5B%7Blabel:%27Dogs%27,data:%5B50,60,70,180,190%5D%7D,%7Blabel:%27Cats%27,data:%5B100,200,300,400,500%5D%7D%5D%7D%7D

As well as:
https://quickchart.io/chart?c={%22type%22%3A%22line%22%2C%22backgroundColor%22%3A%22white%22%2C%22data%22%3A{%22labels%22%3A[%2210%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%2211%22]%2C%22datasets%22%3A[{%22label%22%3A%22Spieler%20gesamt%20pro%20Stunde%22%2C%22data%22%3A[834047%2C1023352%2C1314856%2C1268807%2C1181454%2C1097574%2C1038732%2C1002766%2C1017152%2C882858%2C1195868%2C1058768%2C1092353%2C1138172%2C1135618%2C806452%2C896226%2C1001641%2C1049666%2C1087859%2C1103905%2C1065783%2C991191%2C882758%2C1659566]}]}%2C%22options%22%3A{}}

Interestingly, bar charts work just fine with otherwise identical parameteres (labels & values).
How can I fix this?

**Comment by typpo** [comment]
Thanks for the report @TuxGamer.  I put in a fix 3ac705147e22b5be14fcce36cd09a511e1fc1967 and you should be able to rebuild the image manually or pull v1.4.3 to render your line chart 👍

**Comment by TuxGamer** [comment]
Confirmed working. Wow, your response was fast. Thank you very much :+1:
