### ISSUE TITLE
Trouble using annotations

### ISSUE THREAD

**Issue by pstephenson02** [typpo/quickchart#74]
This is a really great project first of all, so thank you!

The only thing I haven't been able to get working so far is an annotation:

```json
{
    "type": "bar",
    "data": {
        "labels": ["50","75","90","95","99"],
        "datasets": [
            {
                "label": "Environments",
                "backgroundColor": "blue",
                "data": [3,5,10,15,31]
            }
        ]
    },
    "options": {
        "annotation": {
            "annotations": [
                {
                    "value": "25",
                    "scaleID": "y",
                    "display": true,
                    "borderWidth": 4,
                    "type": "line",
                    "mode": "horizontal",
                    "borderColor": "red"
                }
            ]
        }
    }
}
```

After url encoding and rendering, I get
https://quickchart.io/chart?c=%7b%22data%22%3a%7b%22labels%22%3a%5b%2250%22%2c%2275%22%2c%2290%22%2c%2295%22%2c%2299%22%5d%2c%22datasets%22%3a%5b%7b%22label%22%3a%22Environments%22%2c%22backgroundColor%22%3a%22blue%22%2c%22data%22%3a%5b3%2c5%2c10%2c15%2c31%5d%7d%5d%7d%2c%22options%22%3a%7b%22annotation%22%3a%7b%22annotations%22%3a%5b%7b%22value%22%3a%2225%22%2c%22scaleID%22%3a%22y%22%2c%22display%22%3atrue%2c%22borderWidth%22%3a4%2c%22type%22%3a%22line%22%2c%22mode%22%3a%22horizontal%22%2c%22borderColor%22%3a%22red%22%7d%5d%7d%7d%2c%22type%22%3a%22bar%22%7d

which shows my data but not my annotation :( Am I just messing up the structure of the plugin options? I pulled the example from the documentation here: https://quickchart.io/documentation/#annotations-and-labels

Thanks in advance

**Comment by pstephenson02** [comment]
Ok after some trial an error I figured it out. The key was:
```json
    "options": {
        "annotation": {
            "annotations": [
                {
                    "scaleID": "y-axis-0"
                }
            ]
        }
    }
```
I originally had just `y` here, which I had pulled from https://github.com/chartjs/chartjs-plugin-annotation#configuration

Closing!

**Comment by typpo** [comment]
I was messing around with your problem before I saw your update and came to the same conclusion.  It looks like the chartjs-plugin-annotation example is incorrect, or maybe for the non-latest version of Chart.js?  

In any case, I'm glad you were able to get it working!

**Comment by pstephenson02** [comment]
Thanks for such a quick response!
