### ISSUE TITLE
Wrong color drew by docker service

### ISSUE THREAD

**Issue by brucez007** [typpo/quickchart#77]
Hello,
I'm using the same json string, but the color in chart drew by docker service (the latest version) wasn't right. 
Drew by quickchart.io:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/46194610/101734314-0a5cfa80-3afb-11eb-8f8b-81f7f169730a.png">
Drew by docker service:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/46194610/101734356-1b0d7080-3afb-11eb-8780-d6155e9e9127.png">

Here is the online editor link:
https://quickchart.io/sandbox/#%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20defaults%3A%20%7B%0A%20%20%20%20global%3A%20%7B%0A%20%20%20%20%20%20defaultFontSize%3A%209%2C%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%27Jane%20(173.1%25)%27%2C%20%27Greep%20(173.1%25)%27%2C%20%27Michal%20(90%25)%27%2C%20%27Tom%20(170%25)%27%2C%20%27Kim%20(0%25)%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%27Billable%20hours%27%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%27rgba(255%2C%2099%2C%20132%2C%200.5)%27%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%27rgb(255%2C%2099%2C%20132)%27%2C%0A%20%20%20%20%20%20%20%20borderWidth%3A%200.5%2C%0A%20%20%20%20%20%20%20%20stack%3A%20%27Stack%200%27%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B69.5%2C%2063.5%2C%2036%2C%2068%2C%2071.3%2C%2016%2C%2041%2C%2048%2C%2016%2C%2044%2C%200%5D%2C%0A%20%20%20%20%20%20%20%20datalabels%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20display%3A%20%5Btrue%2C%20true%2C%20true%2Ctrue%2Ctrue%2C%20true%2Ctrue%2Ctrue%2Ctrue%2Ctrue%2Cfalse%5D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%27Other%20hours%27%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%27rgba(54%2C%20162%2C%20235%2C%200.5)%27%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%27rgb(54%2C%20162%2C%20235)%27%2C%0A%20%20%20%20%20%20%20%20borderWidth%3A%200.5%2C%0A%20%20%20%20%20%20%20%20stack%3A%20%27Stack%200%27%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B1.5%2C%201.5%2C%2014.5%2C%200.5%2C%201.5%2C%2032%2C%208.5%2C%200%2C%2032%2C%205.5%2C%209%5D%2C%0A%20%20%20%20%20%20%20%20datalabels%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20display%3A%20%5Btrue%2C%20true%2C%20true%2Ctrue%2Ctrue%2C%20true%2Ctrue%2C%20false%2Ctrue%2Ctrue%2C%20true%5D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20%22line%22%2C%0A%20%20%20%20%20%20%20%20label%3A%20%22Utilization%22%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%27rgba(54%2C%20162%2C%2020)%27%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%22rgb(54%2C%20162%2C%2020)%22%2C%0A%20%20%20%20%20%20%20%20borderWidth%3A%200.5%2C%0A%20%20%20%20%20%20%20%20fill%3A%20false%2C%0A%20%20%20%20%20%20%20%20yAxisID%3A%20%22y1%22%2C%0A%20%20%20%20%20%20%20%20lineTension%3A0%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B173.1%2C173.1%2C90%2C170%2C183%2C40%2C101%2C120%2C40%2C110%2C0%5D%2C%0A%20%20%20%20%20%20%20%20datalabels%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20display%3A%20%5Bfalse%2C%20false%2C%20false%2Cfalse%2Cfalse%2C%20false%2Cfalse%2C%20false%2Cfalse%2Cfalse%2C%20false%5D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%2C%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20%22responsive%22%3A%20true%2C%0A%20%20%20%20title%3A%20%7B%0A%20%20%20%20%20%20display%3A%20true%2C%0A%20%20%20%20%20%20text%3A%20%27Time%20report%27%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20legend%3A%20%7B%20labels%3A%20%7B%20fontSize%3A%209%20%7D%7D%2C%0A%20%20%20%20datasets%3A%20%7B%20bar%3A%20%7B%20categoryPercentage%3A%200.6%2C%20barPercentage%3A%200.7%20%7D%20%7D%2C%0A%20%20%20%20scales%3A%20%7B%0A%20%20%20%20%20%20offset%3Atrue%2C%0A%20%20%20%20%20%20xAxes%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20stacked%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20ticks%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20fontSize%3A%209%2C%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20yAxes%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20stacked%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20ticks%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20steps%3A%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20stepValue%3A%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20fontSize%3A%209%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%3A%20%22y1%22%2C%0A%20%20%20%20%20%20%20%20%20%20type%3A%20%22linear%22%2C%0A%20%20%20%20%20%20%20%20%20%20display%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20position%3A%20%22right%22%2C%0A%20%20%20%20%20%20%20%20%20%20gridLines%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20drawOnChartArea%3A%20false%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20ticks%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20fontSize%3A%209%2C%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20plugins%3A%20%7B%0A%20%20%20%20%20%20datalabels%3A%20%7B%0A%20%20%20%20%20%20%20%20anchor%3A%20%27center%27%2C%0A%20%20%20%20%20%20%20%20align%3A%20%27center%27%2C%0A%20%20%20%20%20%20%20%20color%3A%20%27%23000%27%2C%0A%20%20%20%20%20%20%20%20font%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20weight%3A%20%27normal%27%2C%0A%20%20%20%20%20%20%20%20%20%20size%3A%209%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%20%20%0A%20%20%7D%0A%20%20%20%20%0A%7D

**Comment by brucez007** [comment]
My OS: RHCE 7.9 (Maipo), x86_64

**Comment by dompling** [comment]
Hi !
That color is wrong?

**Comment by typpo** [comment]
Thanks @brucez007, this is a known issue as the production service fixes a bug in 
`chartjs-plugin-colorschemes`.  You can work around this by explicitly setting `pointBorderColor` on your line chart dataset ([chartjs docs](https://www.chartjs.org/docs/latest/charts/line.html#dataset-properties)).
