### ISSUE TITLE
Commercial licensing

### ISSUE THREAD

**Issue by lip5201** [typpo/quickchart#79]
See your API document that you need to buy a commercial license to use higher speed and features! Is the open source version fully functional? If there is a higher need, you still need to buy a commercial license?

**Comment by typpo** [comment]
The open source version is fully functional for Chart.js and QR code rendering!  The paid version has some extra features described [here](https://quickchart.io/pricing/) and removes rate limits imposed by the free version hosted on quickchart.io (there are no rate limits if you self-host).  Happy to answer more qs, feel free to email ian@quickchart.io.

**Comment by fabiobeoni** [comment]
Hi @typpo,

the AGPL licence is not very clear to me about the constrains of using the open source version "as-is", in a wider commercial solution. I would appreciate if you can clarify..

I am considering to include quickcharts open source as part of a solution made of several services (docker containers), and I would like to call the self-hosted quickcharts REST API to generate chart images (no modification to the source code at-all).

Can I use quickchart open source as such in a solution with commercial license? If so, is it required to release the source code of my solution?

Many thanks, F.
