### ISSUE TITLE
Not encoding Japanese/Chinese correctly

### ISSUE THREAD

**Issue by choychris** [typpo/quickchart#8]
Hi typpo, 

Once again, thank you for such a useful open source. This project really helps me a lot.
I find that it does not decode Japanese/Chinese character correctly.
Here is a simple example:
```
{
  type: 'bar',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May'],
    datasets: [{
      label: 'こんにちは',
      data: [ 50, 60, 70, 180, 190 ]
    }, {
      label: 'Cats',
      data: [ 100, 200, 300, 400, 500 ]
    }]
  }
}
```
![chart](https://user-images.githubusercontent.com/20982609/55619914-3c697580-57cc-11e9-957a-dd2da1c57af7.png)

Best regards,
Chris

**Comment by typpo** [comment]
Apologies for the delay, the issue should be fixed now!  I've added more unicode fonts to the underlying system.

![image](https://user-images.githubusercontent.com/310310/55757657-7a5fd700-5a22-11e9-9218-f0d7170398a3.png)

**Comment by xuzhen1994** [comment]
Does the docker image support chinese character? 
I run the latest image and found wrong chinese encoding.
![image](https://user-images.githubusercontent.com/6793111/82897774-bb021300-9f8a-11ea-8a6c-25b7cffb71ee.png)
