### ISSUE TITLE
Font color not changeable in "Line" annotation label

### ISSUE THREAD

**Issue by SpencerLawrenceBrown** [typpo/quickchart#81]
Hi,

It seems that the color of the "Line" annotation label is not conforming to the Chart-js API.

In general the "font" property of "label" seems to have no effect. Please let me know how I can fix this.

Chart-js Docs [ref](https://github.com/chartjs/chartjs-plugin-annotation)
```
label: {
        // Background color of label, default below
        backgroundColor: 'rgba(0,0,0,0.8)',

        font: {
            // Font family of text, inherits from global
            family: "sans-serif",

            // Font size of text, inherits from global
            size: 12,

            // Font style of text, default below
            style: "bold",

            // Font color of text, default below
            color: "#fff",
        },
...
```

Example: 
`{
   "type":"bar",
   "data":{
      "labels":[
         "Mon",
         "Tue",
         "Wed",
         "Thurs",
         "Fri"
      ],
      "datasets":[
         {
            "type":"line",
            "label":"Pizzas Eaten",
            "backgroundColor":"rgba(75, 192, 192, 0.5)",
            "borderColor":"rgb(75, 192, 192)",
            "fill":false,
            "data":[
               1,
               2,
               300,
               40,
               90
            ]
         }
      ]
   },
   "options":{
      "annotation":{
         "annotations":[
            {
               "type":"line",
               "mode":"horizontal",
               "scaleID":"y-axis-0",
               "value":24,
               "borderDash":[
                  8,
                  8
               ],
               "borderColor":"green",
               "borderWidth":2,
               "label":{
                  "backgroundColor":"red",
                  "font":{
                     "family":"sans-serif",
                     "size":50,
                     "style":"bold",
                     "color":"#000"
                  },
                  "content":"Minimum Acceptable Pizza",
                  "enabled":true
               }
            }
         ]
      },
      "title":{
         "text":"Chart.js Combo Time Scale"
      },
      "scales":{
         "xAxes":[
            {
               "offset":true
            }
         ]
      }
   }
}
`

In the above example, I expect the label to be black

**Comment by typpo** [comment]
Hi Spencer, you'll have to refer to the documentation from the latest published version of chartjs-plugin-annotation, not the master branch on github.  In the [v0.5.7](https://github.com/chartjs/chartjs-plugin-annotation/tree/v0.5.7#line-annotations), there isn't a `label.font` object and instead the font keys are named `fontFamily`, `fontSize`, `fontStyle`, etc.

For example:
```json
{
    "type": "bar",
    "data": {
        "labels": ["Mon", "Tue", "Wed", "Thurs", "Fri"],
        "datasets": [{
            "type": "line",
            "label": "Pizzas Eaten",
            "backgroundColor": "rgba(75, 192, 192, 0.5)",
            "borderColor": "rgb(75, 192, 192)",
            "fill": false,
            "data": [1, 2, 300, 40, 90]
        }]
    },
    "options": {
        "annotation": {
            "annotations": [{
                "type": "line",
                "mode": "horizontal",
                "scaleID": "y-axis-0",
                "value": 24,
                "borderDash": [8, 8],
                "borderColor": "green",
                "borderWidth": 2,
                "label": {
                    "backgroundColor": "red",
                    "fontFamily": "Noto Mono",
                    "fontSize": 15,
                    "fontStyle": "bold",
                    "fontColor": "#000",
                    "content": "Minimum Acceptable Pizza",
                    "enabled": true
                }
            }]
        },
        "title": {
            "text": "Chart.js Combo Time Scale"
        },
        "scales": {
            "xAxes": [{
                "offset": true
            }]
        }
    }
}
```

![custom chart.js annotation](https://user-images.githubusercontent.com/310310/103190683-058c9a80-48a0-11eb-8720-707cbab9733d.png)

**Comment by SpencerLawrenceBrown** [comment]
@typpo thank you for the quick response!
