### ISSUE TITLE
Add whitespace around chart

### ISSUE THREAD

**Issue by gabenotgave** [typpo/quickchart#82]
Is it possible to add whitespace/padding around a chart without having to do it programmatically? I've explored the QuickChart documentation and came to the conclusion that there are no URL parameters for doing this. Has anybody had to deal with this before? I feel that the x-axis labels are too close to the bottom of the image.

Thanks :)

**Comment by typpo** [comment]
Yes!  Just use `options.layout.padding`.  [Chart.js docs](https://www.chartjs.org/docs/latest/configuration/layout.html).  For example:
```
{
  type: 'bar',
  data: {
    labels: ['Q1', 'Q2', 'Q3', 'Q4'],
    datasets: [{
      label: 'Users',
      data: [50, 60, 70, 180]
    }]
  },
  options: {
    layout: {
      padding: {
        bottom: 50 
      }
    }
  }
}
```

![chart with bottom padding](https://user-images.githubusercontent.com/310310/105637778-06273b00-5e24-11eb-8cb7-089d7928836d.png)

**Comment by gabenotgave** [comment]
This is just what I wanted. Thank you!
