### ISSUE TITLE
Chart output to SVG instead of PNG?

### ISSUE THREAD

**Issue by khang-nd** [typpo/quickchart#85]
Is it possible to achieve this for `/chart`? Thank you.

**Comment by typpo** [comment]
Hey @khang-nd, we recently added SVG support to the hosted version (it'll take a little work to port it over to the Docker container, but that is planned).

You can try it by adding a **format=svg** query parameter to your URL.  For example:

https://quickchart.io/chart?c={type:'bar',data:{labels:[2012,2013,2014,2015,2016],datasets:[{label:'Users',data:[120,60,50,180,120]}]}}&format=svg

**Comment by khang-nd** [comment]
Hello Ian, thank you, that's all I neeeded. I opened a pull request to update accordingly in the JS client lib. Closing this.
