### ISSUE TITLE
Is Gantt chart supported in quickchart? If not is it possible to do so?

### ISSUE THREAD

**Issue by zestllankesh** [typpo/quickchart#9]

**Comment by typpo** [comment]
Quickchart uses the Chart.js rendering library.  I searched for "chart.js gantt" and found this [StackOverflow post](https://stackoverflow.com/questions/41259441/how-to-draw-gantt-chart-using-chart-js-or-other-libraries).

Based on the first response, you could take the following and put it into Quickchart.  It renders like this:

![image](https://user-images.githubusercontent.com/310310/57544251-ad400800-730b-11e9-9a94-2ac3e683cb86.png)
[direct link](https://quickchart.io/chart?bkg=white&c=%7B%0A%20%20type%3A%20%27line%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20borderColor%3A%20%22rgba(246%2C156%2C85%2C1)%22%2C%0A%20%20%20%20%20%20fill%3A%20false%2C%0A%20%20%20%20%20%20borderWidth%3A%2015%2C%0A%20%20%20%20%20%20pointRadius%3A%200%2C%0A%20%20%20%20%20%20data%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20x%3A%200%2C%0A%20%20%20%20%20%20%20%20y%3A%209%0A%20%20%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20x%3A%203%2C%0A%20%20%20%20%20%20%20%20y%3A%209%0A%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20borderColor%3A%20%22rgba(208%2C255%2C154%2C1)%22%2C%0A%20%20%20%20%20%20fill%3A%20false%2C%0A%20%20%20%20%20%20borderWidth%3A%2015%2C%0A%20%20%20%20%20%20pointRadius%3A%200%2C%0A%20%20%20%20%20%20data%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20x%3A%203%2C%0A%20%20%20%20%20%20%20%20y%3A%207%0A%20%20%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20x%3A%205%2C%0A%20%20%20%20%20%20%20%20y%3A%207%0A%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20borderColor%3A%20%22rgba(246%2C156%2C85%2C1)%22%2C%0A%20%20%20%20%20%20fill%3A%20false%2C%0A%20%20%20%20%20%20borderWidth%3A%2015%2C%0A%20%20%20%20%20%20pointRadius%3A%200%2C%0A%20%20%20%20%20%20data%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20x%3A%205%2C%0A%20%20%20%20%20%20%20%20y%3A%205%0A%20%20%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20x%3A%2010%2C%0A%20%20%20%20%20%20%20%20y%3A%205%0A%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20borderColor%3A%20%22rgba(208%2C255%2C154%2C1)%22%2C%0A%20%20%20%20%20%20fill%3A%20false%2C%0A%20%20%20%20%20%20borderWidth%3A%2015%2C%0A%20%20%20%20%20%20pointRadius%3A%200%2C%0A%20%20%20%20%20%20data%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20x%3A%2010%2C%0A%20%20%20%20%20%20%20%20y%3A%203%0A%20%20%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20%20%20x%3A%2013%2C%0A%20%20%20%20%20%20%20%20y%3A%203%0A%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%5D%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20legend%3A%20%7B%0A%20%20%20%20%20%20display%3A%20false%0A%20%20%20%20%7D%2C%0A%20%20%20%20scales%3A%20%7B%0A%20%20%20%20%20%20xAxes%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20type%3A%20%27linear%27%2C%0A%20%20%20%20%20%20%20%20ticks%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20beginAtzero%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20stepSize%3A%201%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%5D%2C%0A%20%20%20%20%20%20yAxes%3A%20%5B%7B%0A%20%20%20%20%20%20%20%20scaleLabel%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20display%3A%20false%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20ticks%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20beginAtZero%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20max%3A%2010%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%5D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

This chart.js adaptation is not as aesthetically pleasing as other gantt chart libraries, but it's a start.

```
{
  type: 'line',
  data: {
    datasets: [{
      borderColor: "rgba(246,156,85,1)",
      fill: false,
      borderWidth: 15,
      pointRadius: 0,
      data: [{
        x: 0,
        y: 9
      }, {
        x: 3,
        y: 9
      }]
    }, {
      borderColor: "rgba(208,255,154,1)",
      fill: false,
      borderWidth: 15,
      pointRadius: 0,
      data: [{
        x: 3,
        y: 7
      }, {
        x: 5,
        y: 7
      }]
    }, {
      borderColor: "rgba(246,156,85,1)",
      fill: false,
      borderWidth: 15,
      pointRadius: 0,
      data: [{
        x: 5,
        y: 5
      }, {
        x: 10,
        y: 5
      }]
    }, {
      borderColor: "rgba(208,255,154,1)",
      fill: false,
      borderWidth: 15,
      pointRadius: 0,
      data: [{
        x: 10,
        y: 3
      }, {
        x: 13,
        y: 3
      }]
    }]
  },
  options: {
    legend: {
      display: false
    },
    scales: {
      xAxes: [{
        type: 'linear',
        ticks: {
          beginAtzero: true,
          stepSize: 1
        }
      }],
      yAxes: [{
        scaleLabel: {
          display: false
        },
        ticks: {
          beginAtZero: true,
          max: 10
        }
      }]
    }
  }
}
```

**Comment by zestllankesh** [comment]
Cool. Will give this a try.

Thanks for taking time for responding 

Cheers :beer:
