### ISSUE TITLE
Update to ChartJS V3

### ISSUE THREAD

**Issue by kartblanch** [typpo/quickchart#94]
Hi!
Are you planning to update quickchart to ChartJS V3?

**Comment by typpo** [comment]
Yes, this is planned!

**Comment by typpo** [comment]
Chart.js v3 support has been added to this repo :)  Add the URL query param e.g. `version=3` or `version=3.4.1` to render with v3.

**Comment by hoar1715** [comment]
is chartjs-plugin-datalabels work with Chart.js v3?

**Comment by typpo** [comment]
No, the plugin does not support v3 right now.

**Comment by hoar1715** [comment]
Could you add this plugin to v3?

**Comment by typpo** [comment]
Unfortunately not, because the plugin does not support v3.

**Comment by hoar1715** [comment]
the plugin is supported v3 now.
https://github.com/chartjs/chartjs-plugin-datalabels/discussions/213
https://jsfiddle.net/31u7ya59/1/

**Comment by typpo** [comment]
Support for Datalabels + Chart.js v3 has been added to quickchart.io (hosted version).  The change will be ported to this repo.

For example:
```
{
  type: 'bar',
  data: {
    labels: ['Q1', 'Q2', 'Q3', 'Q4'],
    datasets: [{
      label: 'Data',
      data: [50, 60, 70, 180]
    }]
  },
  options: {
    plugins: {
      annotation: {
        annotations: {
          box1: {
            type: 'box',
            xMin: 0,
            xMax: 2,
            yMin: 80,
            yMax: 120,
            backgroundColor: '#f00',
          }
        }
      }
    }
  }
}
```
[link to chart (chart.js v3)](https://quickchart.io/chart?c=%7B%0A%20%20type%3A%20%27bar%27%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%27Q1%27%2C%20%27Q2%27%2C%20%27Q3%27%2C%20%27Q4%27%5D%2C%0A%20%20%20%20datasets%3A%20%5B%7B%0A%20%20%20%20%20%20label%3A%20%27Data%27%2C%0A%20%20%20%20%20%20data%3A%20%5B50%2C%2060%2C%2070%2C%20180%5D%0A%20%20%20%20%7D%5D%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20plugins%3A%20%7B%0A%20%20%20%20%20%20annotation%3A%20%7B%0A%20%20%20%20%20%20%20%20annotations%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20box1%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20%27box%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20xMin%3A%200%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20xMax%3A%202%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20yMin%3A%2080%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20yMax%3A%20120%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20%27%23f00%27%2C%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&v=3)
![image](https://user-images.githubusercontent.com/310310/129051816-03ec2433-97eb-42a6-ab88-7adb11a79524.png)
