### ISSUE TITLE
Chart type "progressBar" is not a chart type

### ISSUE THREAD

**Issue by tomuky2k** [typpo/quickchart#97]
Hi,

I'm posting (with Postman) to http://0.0.0.0/chart with the following JSON:

{
    "chart": {
        "type": "progressBar",
        "data": {"datasets": [{"data": [50]}]}
    }
}

The message I get back is:
        Chart Error: "progressBar" is not a chart type.

I can use both the healthcheck endpoints, including /healthcheck/chart to produce a chart, or use JSON to produce a bar chart. My healthcheck response is:

{"success":true,"version":"1.4.3"}

I expect the answer is, that this chart type is not available in open source / github version.

Thank you

Tom

**Comment by typpo** [comment]
Hi Tom,

I've just added progressBar support in a02f34a to synchronize with capabilities on quickchart.io.  Note that the `progressBar` type is a special-cased `horizontalBar` chart.  I'd been holding off because it really should be rewritten as a Chart.js plugin.
